<a href="https://colab.research.google.com/github/Bilclay/max_data/blob/Bilclay-DS-1/Max_data_week3_(Data_Engineering)_SQL_Notebook_Example_py%EC%9D%98_%EC%82%AC%EB%B3%B8.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Set up Configuration

In [1]:
%load_ext sql

In [2]:
# ID와 PW를 자신의 환경에 맞게 수정
%sql postgresql://ID:PW!1@주소

/usr/local/lib/python3.6/dist-packages/psycopg2/__init__.py:144: UserWarning: The psycopg2 wheel package will be renamed from release 2.8; in order to keep installing from binary please use "pip install psycopg2-binary" instead. For details see: <http://initd.org/psycopg/docs/install.html#binary-install-from-pypi>.
  """)

'Connected: gayoungjang@dev'

Example of Running a SQL:  
이후 아래 SQL에서 스키마는 자신의 스키마로 변경

In [3]:
%%sql

SELECT * FROM raw_data.session_timestamp LIMIT 10

 * postgresql://gayoungjang:***@grepp-data.cduaw970ssvt.ap-northeast-2.redshift.amazonaws.com:5439/dev
10 rows affected.

[('7cdace91c487558e27ce54df7cdb299c', datetime.datetime(2019, 5, 1, 0, 13, 11, 783000)),
 ('94f192dee566b018e0acf31e1f99a2d9', datetime.datetime(2019, 5, 1, 0, 49, 46, 73000)),
 ('7ed2d3454c5eea71148b11d0c25104ff', datetime.datetime(2019, 5, 1, 10, 18, 43, 210000)),
 ('f1daf122cde863010844459363cd31db', datetime.datetime(2019, 5, 1, 13, 10, 56, 413000)),
 ('fd0efcca272f704a760c3b61dcc70fd0', datetime.datetime(2019, 5, 1, 13, 45, 19, 793000)),
 ('8804f94e16ba5b680e239a554a08f7d2', datetime.datetime(2019, 5, 1, 14, 23, 7, 660000)),
 ('c5f441cd5f43eb2f2c024e1f8b5d00cd', datetime.datetime(2019, 5, 1, 15, 3, 54, 650000)),
 ('d5fcc35c94879a4afad61cacca56192c', datetime.datetime(2019, 5, 1, 15, 13, 16, 140000)),
 ('3d191ef6e236bd1b9bdb9ff4743c47fe', datetime.datetime(2019, 5, 1, 15, 33, 58, 197000)),
 ('c17028c9b6e0c5deaad29665d582284a', datetime.datetime(2019, 5, 1, 15, 59, 57, 490000))]

Example of Converting a SQL result into Pandas Dataframe

In [4]:
result = %sql SELECT * FROM raw_data.channel
df = result.DataFrame()

 * postgresql://gayoungjang:***@grepp-data.cduaw970ssvt.ap-northeast-2.redshift.amazonaws.com:5439/dev
7 rows affected.

In [5]:
df.head()

  channelname
0     Organic
1      Google
2       Naver
3    Facebook
4     Youtube

3주차 과정 첫번째 예제 - p19 연습

In [7]:
%%sql

CREATE TABLE gayoungjang.create_channel (
   channel varchar(32) primary key
);

 * postgresql://gayoungjang:***@grepp-data.cduaw970ssvt.ap-northeast-2.redshift.amazonaws.com:5439/dev
Done.

[]

In [8]:
%%sql

INSERT INTO gayoungjang.create_channel VALUES ('FACEBOOK'), ('GOOGLE');

 * postgresql://gayoungjang:***@grepp-data.cduaw970ssvt.ap-northeast-2.redshift.amazonaws.com:5439/dev
2 rows affected.

[]

In [9]:
%%sql

SELECT * FROM gayoungjang.create_channel;

 * postgresql://gayoungjang:***@grepp-data.cduaw970ssvt.ap-northeast-2.redshift.amazonaws.com:5439/dev
2 rows affected.

[('FACEBOOK',), ('GOOGLE',)]

In [10]:
%%sql

CREATE TABLE gayoungjang.session_summary AS SELECT TO_CHAR(ts, 'YYYY-MM') AS month, COUNT(DISTINCT userid)
FROM raw_data.user_session_channel A
JOIN raw_data.session_timestamp B ON A.sessionid = B.sessionid
GROUP BY 1
ORDER BY 1 DESC;

 * postgresql://gayoungjang:***@grepp-data.cduaw970ssvt.ap-northeast-2.redshift.amazonaws.com:5439/dev
Done.

[]

In [11]:
%%sql

SELECT * FROM gayoungjang.session_summary;

 * postgresql://gayoungjang:***@grepp-data.cduaw970ssvt.ap-northeast-2.redshift.amazonaws.com:5439/dev
7 rows affected.

[('2019-10', 763),
 ('2019-09', 639),
 ('2019-07', 623),
 ('2019-06', 459),
 ('2019-05', 281),
 ('2019-11', 721),
 ('2019-08', 662)]

In [12]:
%%sql

DROP TABLE gayoungjang.session_summary

 * postgresql://gayoungjang:***@grepp-data.cduaw970ssvt.ap-northeast-2.redshift.amazonaws.com:5439/dev
Done.

[]

In [21]:
%%sql 

ALTER TABLE gayoungjang.create_channel RENAME channel to channelname

 * postgresql://gayoungjang:***@grepp-data.cduaw970ssvt.ap-northeast-2.redshift.amazonaws.com:5439/dev
Done.

[]

In [22]:
%%sql

INSERT INTO gayoungjang.create_channel VALUES ('TIKTOK')

 * postgresql://gayoungjang:***@grepp-data.cduaw970ssvt.ap-northeast-2.redshift.amazonaws.com:5439/dev
1 rows affected.

[]

In [23]:
%%sql 

SELECT *
FROM gayoungjang.create_channel

 * postgresql://gayoungjang:***@grepp-data.cduaw970ssvt.ap-northeast-2.redshift.amazonaws.com:5439/dev
3 rows affected.

[('FACEBOOK',), ('GOOGLE',), ('TIKTOK',)]

3주차 과정 두번째 예제 - p22 연습
LIKE is a case sensitive string match. ILIKE is a case-insensitive string match

In [26]:
%%sql

SELECT COUNT(1)
FROM raw_data.user_session_channel
WHERE channel in ('Google','Facebook');

 * postgresql://gayoungjang:***@grepp-data.cduaw970ssvt.ap-northeast-2.redshift.amazonaws.com:5439/dev
1 rows affected.

[(33773,)]

In [27]:
%%sql

SELECT COUNT(1)
FROM raw_data.user_session_channel
WHERE channel like 'Google' or channel ilike 'Facebook'

 * postgresql://gayoungjang:***@grepp-data.cduaw970ssvt.ap-northeast-2.redshift.amazonaws.com:5439/dev
1 rows affected.

[(33773,)]

In [29]:
%%sql

SELECT DISTINCT channel
FROM raw_data.user_session_channel
WHERE channel ilike '%o%'

 * postgresql://gayoungjang:***@grepp-data.cduaw970ssvt.ap-northeast-2.redshift.amazonaws.com:5439/dev
4 rows affected.

[('Facebook',), ('Youtube',), ('Organic',), ('Google',)]

In [30]:
%%sql

SELECT DISTINCT channel
FROM raw_data.user_session_channel
WHERE channel NOT ILIKE '%o%'

 * postgresql://gayoungjang:***@grepp-data.cduaw970ssvt.ap-northeast-2.redshift.amazonaws.com:5439/dev
2 rows affected.

[('Naver',), ('Instagram',)]

In [32]:
%%sql 
--p23 연습

SELECT LEN(channelname), UPPER(channelname), LOWER(channelname), LEFT(channelname, 4)
FROM gayoungjang.create_channel

 * postgresql://gayoungjang:***@grepp-data.cduaw970ssvt.ap-northeast-2.redshift.amazonaws.com:5439/dev
3 rows affected.

[(8, 'FACEBOOK', 'facebook', 'FACE'),
 (6, 'GOOGLE', 'google', 'GOOG'),
 (6, 'TIKTOK', 'tiktok', 'TIKT')]

SQL 연습: session이 가장 많이 생성되는 시간대? - p27

In [35]:
%%sql 

select pg_timezone_names();

 * postgresql://gayoungjang:***@grepp-data.cduaw970ssvt.ap-northeast-2.redshift.amazonaws.com:5439/dev
600 rows affected.

[('(PST8PDT,PDT,-07:00:00,t)',),
 ('(Asia/Muscat,+04,04:00:00,f)',),
 ('(Asia/Barnaul,+07,07:00:00,f)',),
 ('(Asia/Dubai,+04,04:00:00,f)',),
 ('(Asia/Kathmandu,+0545,05:45:00,f)',),
 ('(Asia/Aqtau,+05,05:00:00,f)',),
 ('(Asia/Kabul,+0430,04:30:00,f)',),
 ('(Asia/Ujung_Pandang,WITA,08:00:00,f)',),
 ('(Asia/Irkutsk,+08,08:00:00,f)',),
 ('(Asia/Famagusta,EET,02:00:00,f)',),
 ('(Asia/Brunei,+08,08:00:00,f)',),
 ('(Asia/Shanghai,CST,08:00:00,f)',),
 ('(Asia/Chongqing,CST,08:00:00,f)',),
 ('(Asia/Kolkata,IST,05:30:00,f)',),
 ('(Asia/Urumqi,+06,06:00:00,f)',),
 ('(Asia/Ulaanbaatar,+08,08:00:00,f)',),
 ('(Asia/Thimbu,+06,06:00:00,f)',),
 ('(Asia/Dili,+09,09:00:00,f)',),
 ('(Asia/Beirut,EET,02:00:00,f)',),
 ('(Asia/Macau,CST,08:00:00,f)',),
 ('(Asia/Kuala_Lumpur,+08,08:00:00,f)',),
 ('(Asia/Dacca,+06,06:00:00,f)',),
 ('(Asia/Damascus,EET,02:00:00,f)',),
 ('(Asia/Kamchatka,+12,12:00:00,f)',),
 ('(Asia/Calcutta,IST,05:30:00,f)',),
 ('(Asia/Tashkent,+05,05:00:00,f)',),
 ('(Asia/Seoul,KST,09:00:00,f)',),
 ('(Asia/Vientiane,+07,07:00:00,f)',),
 ('(Asia/Qostanay,+06,06:00:00,f)',),
 ('(Asia/Bangkok,+07,07:00:00,f)',),
 ('(Asia/Atyrau,+05,05:00:00,f)',),
 ('(Asia/Samarkand,+05,05:00:00,f)',),
 ('(Asia/Rangoon,+0630,06:30:00,f)',),
 ('(Asia/Nicosia,EET,02:00:00,f)',),
 ('(Asia/Chita,+09,09:00:00,f)',),
 ('(Asia/Hebron,EEST,03:00:00,t)',),
 ('(Asia/Hong_Kong,HKT,08:00:00,f)',),
 ('(Asia/Karachi,PKT,05:00:00,f)',),
 ('(Asia/Phnom_Penh,+07,07:00:00,f)',),
 ('(Asia/Riyadh88,zzz,03:07:04,f)',),
 ('(Asia/Tokyo,JST,09:00:00,f)',),
 ('(Asia/Bahrain,+03,03:00:00,f)',),
 ('(Asia/Yekaterinburg,+05,05:00:00,f)',),
 ('(Asia/Chungking,CST,08:00:00,f)',),
 ('(Asia/Bishkek,+06,06:00:00,f)',),
 ('(Asia/Hovd,+07,07:00:00,f)',),
 ('(Asia/Srednekolymsk,+11,11:00:00,f)',),
 ('(Asia/Harbin,CST,08:00:00,f)',),
 ('(Asia/Riyadh87,zzz,03:07:04,f)',),
 ('(Asia/Yakutsk,+09,09:00:00,f)',),
 ('(Asia/Krasnoyarsk,+07,07:00:00,f)',),
 ('(Asia/Choibalsan,+08,08:00:00,f)',),
 ('(Asia/Ust-Nera,+10,10:00:00,f)',),
 ('(Asia/Jayapura,WIT,09:00:00,f)',),
 ('(Asia/Kuching,+08,08:00:00,f)',),
 ('(Asia/Ashgabat,+05,05:00:00,f)',),
 ('(Asia/Khandyga,+09,09:00:00,f)',),
 ('(Asia/Kashgar,+06,06:00:00,f)',),
 ('(Asia/Singapore,+08,08:00:00,f)',),
 ('(Asia/Colombo,+0530,05:30:00,f)',),
 ('(Asia/Jerusalem,IST,02:00:00,f)',),
 ('(Asia/Dhaka,+06,06:00:00,f)',),
 ('(Asia/Jakarta,WIB,07:00:00,f)',),
 ('(Asia/Tomsk,+07,07:00:00,f)',),
 ('(Asia/Dushanbe,+05,05:00:00,f)',),
 ('(Asia/Makassar,WITA,08:00:00,f)',),
 ('(Asia/Riyadh,+03,03:00:00,f)',),
 ('(Asia/Istanbul,+03,03:00:00,f)',),
 ('(Asia/Tel_Aviv,IST,02:00:00,f)',),
 ('(Asia/Tehran,+0330,03:30:00,f)',),
 ('(Asia/Manila,PST,08:00:00,f)',),
 ('(Asia/Saigon,+07,07:00:00,f)',),
 ('(Asia/Gaza,EEST,03:00:00,t)',),
 ('(Asia/Anadyr,+12,12:00:00,f)',),
 ('(Asia/Qatar,+03,03:00:00,f)',),
 ('(Asia/Aden,+03,03:00:00,f)',),
 ('(Asia/Baku,+04,04:00:00,f)',),
 ('(Asia/Almaty,+06,06:00:00,f)',),
 ('(Asia/Riyadh89,zzz,03:07:04,f)',),
 ('(Asia/Vladivostok,+10,10:00:00,f)',),
 ('(Asia/Macao,CST,08:00:00,f)',),
 ('(Asia/Katmandu,+0545,05:45:00,f)',),
 ('(Asia/Taipei,CST,08:00:00,f)',),
 ('(Asia/Amman,EET,02:00:00,f)',),
 ('(Asia/Ashkhabad,+05,05:00:00,f)',),
 ('(Asia/Baghdad,+03,03:00:00,f)',),
 ('(Asia/Ho_Chi_Minh,+07,07:00:00,f)',),
 ('(Asia/Aqtobe,+05,05:00:00,f)',),
 ('(Asia/Qyzylorda,+05,05:00:00,f)',),
 ('(Asia/Omsk,+06,06:00:00,f)',),
 ('(Asia/Yerevan,+04,04:00:00,f)',),
 ('(Asia/Ulan_Bator,+08,08:00:00,f)',),
 ('(Asia/Pontianak,WIB,07:00:00,f)',),
 ('(Asia/Sakhalin,+11,11:00:00,f)',),
 ('(Asia/Yangon,+0630,06:30:00,f)',),
 ('(Asia/Pyongyang,KST,09:00:00,f)',),
 ('(Asia/Novokuznetsk,+07,07:00:00,f)',),
 ('(Asia/Oral,+05,05:00:00,f)',),
 ('(Asia/Tbilisi,+04,04:00:00,f)',),
 ('(Asia/Kuwait,+03,03:00:00,f)',),
 ('(Asia/Novosibirsk,+07,07:00:00,f)',),
 ('(Asia/Magadan,+11,11:00:00,f)',),
 ('(Asia/Thimphu,+06,06:00:00,f)',),
 ('(HST,HST,-10:00:00,f)',),
 ('(US/Michigan,EDT,-04:00:00,t)',),
 ('(US/Pacific-New,PDT,-07:00:00,t)',),
 ('(US/Arizona,MST,-07:00:00,f)',),
 ('(US/Central,CDT,-05:00:00,t)',),
 ('(US/Alaska,AKDT,-08:00:00,t)',),
 ('(US/Aleutian,HDT,-09:00:00,t)',),
 ('(US/East-Indiana,EDT,-04:00:00,t)',),
 ('(US/Mountain,MDT,-06:00:00,t)',),
 ('(US/Eastern,EDT,-04:00:00,t)',),
 ('(US/Indiana-Starke,CDT,-05:00:00,t)',),
 ('(US/Pacific,PDT,-07:00:00,t)',),
 ('(US/Hawaii,HST,-10:00:00,f)',),
 ('(US/Samoa,SST,-11:00:00,f)',),
 ('(Iran,+0330,03:30:00,f)',),
 ('(Navajo,MDT,-06:00:00,t)',),
 ('(Zulu,UTC,00:00:00,f)',),
 ('(Eire,GMT,00:00:00,t)',),
 ('(NZ,NZDT,13:00:00,t)',),
 ('(Universal,UTC,00:00:00,f)',),
 ('(Turkey,+03,03:00:00,f)',),
 ('(Iceland,GMT,00:00:00,f)',),
 ('(Australia/Canberra,AEDT,11:00:00,t)',),
 ('(Australia/Victoria,AEDT,11:00:00,t)',),
 ('(Australia/West,AWST,08:00:00,f)',),
 ('(Australia/Sydney,AEDT,11:00:00,t)',),
 ('(Australia/LHI,+11,11:00:00,t)',),
 ('(Australia/South,ACDT,10:30:00,t)',),
 ('(Australia/Eucla,+0845,08:45:00,f)',),
 ('(Australia/Brisbane,AEST,10:00:00,f)',),
 ('(Australia/NSW,AEDT,11:00:00,t)',),
 ('(Australia/Melbourne,AEDT,11:00:00,t)',),
 ('(Australia/Adelaide,ACDT,10:30:00,t)',),
 ('(Australia/Broken_Hill,ACDT,10:30:00,t)',),
 ('(Australia/Darwin,ACST,09:30:00,f)',),
 ('(Australia/ACT,AEDT,11:00:00,t)',),
 ('(Australia/Lindeman,AEST,10:00:00,f)',),
 ('(Australia/Queensland,AEST,10:00:00,f)',),
 ('(Australia/Lord_Howe,+11,11:00:00,t)',),
 ('(Australia/Hobart,AEDT,11:00:00,t)',),
 ('(Australia/Tasmania,AEDT,11:00:00,t)',),
 ('(Australia/North,ACST,09:30:00,f)',),
 ('(Australia/Currie,AEDT,11:00:00,t)',),
 ('(Australia/Yancowinna,ACDT,10:30:00,t)',),
 ('(Australia/Perth,AWST,08:00:00,f)',),
 ('(Chile/Continental,-03,-03:00:00,t)',),
 ('(Chile/EasterIsland,-05,-05:00:00,t)',),
 ('(UCT,UTC,00:00:00,f)',),
 ('(America/Fort_Nelson,MST,-07:00:00,f)',),
 ('(America/Scoresbysund,-01,-01:00:00,f)',),
 ('(America/Hermosillo,MST,-07:00:00,f)',),
 ('(America/Cayman,EST,-05:00:00,f)',),
 ('(America/Guadeloupe,AST,-04:00:00,f)',),
 ('(America/Santo_Domingo,AST,-04:00:00,f)',),
 ('(America/Fort_Wayne,EDT,-04:00:00,t)',),
 ('(America/St_Lucia,AST,-04:00:00,f)',),
 ('(America/Paramaribo,-03,-03:00:00,f)',),
 ('(America/Lima,-05,-05:00:00,f)',),
 ('(America/Yellowknife,MDT,-06:00:00,t)',),
 ('(America/Ojinaga,MDT,-06:00:00,t)',),
 ('(America/Port-au-Prince,EDT,-04:00:00,t)',),
 ('(America/Phoenix,MST,-07:00:00,f)',),
 ('(America/Bahia_Banderas,CST,-06:00:00,f)',),
 ('(America/Mexico_City,CST,-06:00:00,f)',),
 ('(America/Nipigon,EDT,-04:00:00,t)',),
 ('(America/Boa_Vista,-04,-04:00:00,f)',),
 ('(America/Rankin_Inlet,CDT,-05:00:00,t)',),
 ('(America/St_Johns,NDT,-02:30:00,t)',),
 ('(America/Puerto_Rico,AST,-04:00:00,f)',),
 ('(America/Grand_Turk,EDT,-04:00:00,t)',),
 ('(America/Rio_Branco,-05,-05:00:00,f)',),
 ('(America/Grenada,AST,-04:00:00,f)',),
 ('(America/Nome,AKDT,-08:00:00,t)',),
 ('(America/Kralendijk,AST,-04:00:00,f)',),
 ('(America/Fortaleza,-03,-03:00:00,f)',),
 ('(America/Dominica,AST,-04:00:00,f)',),
 ('(America/Montreal,EDT,-04:00:00,t)',),
 ('(America/Atka,HDT,-09:00:00,t)',),
 ('(America/Danmarkshavn,GMT,00:00:00,f)',),
 ('(America/Indiana/Winamac,EDT,-04:00:00,t)',),
 ('(America/Indiana/Petersburg,EDT,-04:00:00,t)',),
 ('(America/Indiana/Indianapolis,EDT,-04:00:00,t)',),
 ('(America/Indiana/Vincennes,EDT,-04:00:00,t)',),
 ('(America/Indiana/Knox,CDT,-05:00:00,t)',),
 ('(America/Indiana/Marengo,EDT,-04:00:00,t)',),
 ('(America/Indiana/Vevay,EDT,-04:00:00,t)',),
 ('(America/Indiana/Tell_City,CDT,-05:00:00,t)',),
 ('(America/Indianapolis,EDT,-04:00:00,t)',),
 ('(America/Mazatlan,MST,-07:00:00,f)',),
 ('(America/Swift_Current,CST,-06:00:00,f)',),
 ('(America/Mendoza,-03,-03:00:00,f)',),
 ('(America/Los_Angeles,PDT,-07:00:00,t)',),
 ('(America/Recife,-03,-03:00:00,f)',),
 ('(America/Port_of_Spain,AST,-04:00:00,f)',),
 ('(America/Santa_Isabel,PDT,-07:00:00,t)',),
 ('(America/Metlakatla,AKDT,-08:00:00,t)',),
 ('(America/Juneau,AKDT,-08:00:00,t)',),
 ('(America/Denver,MDT,-06:00:00,t)',),
 ('(America/Dawson_Creek,MST,-07:00:00,f)',),
 ('(America/Guayaquil,-05,-05:00:00,f)',),
 ('(America/Detroit,EDT,-04:00:00,t)',),
 ('(America/Tegucigalpa,CST,-06:00:00,f)',),
 ('(America/Glace_Bay,ADT,-03:00:00,t)',),
 ('(America/New_York,EDT,-04:00:00,t)',),
 ('(America/Boise,MDT,-06:00:00,t)',),
 ('(America/Rosario,-03,-03:00:00,f)',),
 ('(America/Virgin,AST,-04:00:00,f)',),
 ('(America/Bogota,-05,-05:00:00,f)',),
 ('(America/Noronha,-02,-02:00:00,f)',),
 ('(America/Jujuy,-03,-03:00:00,f)',),
 ('(America/Costa_Rica,CST,-06:00:00,f)',),
 ('(America/Barbados,AST,-04:00:00,f)',),
 ('(America/Louisville,EDT,-04:00:00,t)',),
 ('(America/Menominee,CDT,-05:00:00,t)',),
 ('(America/Montevideo,-03,-03:00:00,f)',),
 ('(America/St_Kitts,AST,-04:00:00,f)',),
 ('(America/El_Salvador,CST,-06:00:00,f)',),
 ('(America/Ensenada,PDT,-07:00:00,t)',),
 ('(America/Monterrey,CST,-06:00:00,f)',),
 ('(America/Guatemala,CST,-06:00:00,f)',),
 ('(America/Argentina/ComodRivadavia,-03,-03:00:00,f)',),
 ('(America/Argentina/Mendoza,-03,-03:00:00,f)',),
 ('(America/Argentina/Salta,-03,-03:00:00,f)',),
 ('(America/Argentina/Jujuy,-03,-03:00:00,f)',),
 ('(America/Argentina/San_Luis,-03,-03:00:00,f)',),
 ('(America/Argentina/La_Rioja,-03,-03:00:00,f)',),
 ('(America/Argentina/Cordoba,-03,-03:00:00,f)',),
 ('(America/Argentina/Catamarca,-03,-03:00:00,f)',),
 ('(America/Argentina/Rio_Gallegos,-03,-03:00:00,f)',),
 ('(America/Argentina/San_Juan,-03,-03:00:00,f)',),
 ('(America/Argentina/Ushuaia,-03,-03:00:00,f)',),
 ('(America/Argentina/Buenos_Aires,-03,-03:00:00,f)',),
 ('(America/Argentina/Tucuman,-03,-03:00:00,f)',),
 ('(America/Merida,CST,-06:00:00,f)',),
 ('(America/St_Vincent,AST,-04:00:00,f)',),
 ('(America/Caracas,-04,-04:00:00,f)',),
 ('(America/Cambridge_Bay,MDT,-06:00:00,t)',),
 ('(America/Shiprock,MDT,-06:00:00,t)',),
 ('(America/Sitka,AKDT,-08:00:00,t)',),
 ('(America/Cordoba,-03,-03:00:00,f)',),
 ('(America/Matamoros,CDT,-05:00:00,t)',),
 ('(America/Moncton,ADT,-03:00:00,t)',),
 ('(America/Atikokan,EST,-05:00:00,f)',),
 ('(America/Punta_Arenas,-03,-03:00:00,f)',),
 ('(America/St_Thomas,AST,-04:00:00,f)',),
 ('(America/Aruba,AST,-04:00:00,f)',),
 ('(America/Blanc-Sablon,AST,-04:00:00,f)',),
 ('(America/Chicago,CDT,-05:00:00,t)',),
 ('(America/Knox_IN,CDT,-05:00:00,t)',),
 ('(America/Chihuahua,MST,-07:00:00,f)',),
 ('(America/Winnipeg,CDT,-05:00:00,t)',),
 ('(America/Anguilla,AST,-04:00:00,f)',),
 ('(America/Catamarca,-03,-03:00:00,f)',),
 ('(America/Nassau,EDT,-04:00:00,t)',),
 ('(America/Cancun,EST,-05:00:00,f)',),
 ('(America/Anchorage,AKDT,-08:00:00,t)',),
 ('(America/Adak,HDT,-09:00:00,t)',),
 ('(America/Iqaluit,EDT,-04:00:00,t)',),
 ('(America/Regina,CST,-06:00:00,f)',),
 ('(America/Maceio,-03,-03:00:00,f)',),
 ('(America/Bahia,-03,-03:00:00,f)',),
 ('(America/Porto_Acre,-05,-05:00:00,f)',),
 ('(America/Vancouver,PDT,-07:00:00,t)',),
 ('(America/Pangnirtung,EDT,-04:00:00,t)',),
 ('(America/Whitehorse,PDT,-07:00:00,t)',),
 ('(America/Jamaica,EST,-05:00:00,f)',),
 ('(America/Thunder_Bay,EDT,-04:00:00,t)',),
 ('(America/Santarem,-03,-03:00:00,f)',),
 ('(America/Yakutat,AKDT,-08:00:00,t)',),
 ('(America/Eirunepe,-05,-05:00:00,f)',),
 ('(America/La_Paz,-04,-04:00:00,f)',),
 ('(America/Thule,ADT,-03:00:00,t)',),
 ('(America/Miquelon,-02,-02:00:00,t)',),
 ('(America/Cayenne,-03,-03:00:00,f)',),
 ('(America/Araguaina,-03,-03:00:00,f)',),
 ('(America/Halifax,ADT,-03:00:00,t)',),
 ('(America/Sao_Paulo,-03,-03:00:00,f)',),
 ('(America/Cuiaba,-04,-04:00:00,f)',),
 ('(America/Curacao,AST,-04:00:00,f)',),
 ('(America/Manaus,-04,-04:00:00,f)',),
 ('(America/Montserrat,AST,-04:00:00,f)',),
 ('(America/Marigot,AST,-04:00:00,f)',),
 ('(America/Tijuana,PDT,-07:00:00,t)',),
 ('(America/Antigua,AST,-04:00:00,f)',),
 ('(America/Lower_Princes,AST,-04:00:00,f)',),
 ('(America/Belize,CST,-06:00:00,f)',),
 ('(America/Campo_Grande,-04,-04:00:00,f)',),
 ('(America/Dawson,PDT,-07:00:00,t)',),
 ('(America/North_Dakota/Center,CDT,-05:00:00,t)',),
 ('(America/North_Dakota/New_Salem,CDT,-05:00:00,t)',),
 ('(America/North_Dakota/Beulah,CDT,-05:00:00,t)',),
 ('(America/Guyana,-04,-04:00:00,f)',),
 ('(America/Toronto,EDT,-04:00:00,t)',),
 ('(America/Porto_Velho,-04,-04:00:00,f)',),
 ('(America/Belem,-03,-03:00:00,f)',),
 ('(America/Havana,CDT,-04:00:00,t)',),
 ('(America/Godthab,-03,-03:00:00,f)',),
 ('(America/Asuncion,-03,-03:00:00,t)',),
 ('(America/Resolute,CDT,-05:00:00,t)',),
 ('(America/Tortola,AST,-04:00:00,f)',),
 ('(America/Buenos_Aires,-03,-03:00:00,f)',),
 ('(America/Coral_Harbour,EST,-05:00:00,f)',),
 ('(America/Inuvik,MDT,-06:00:00,t)',),
 ('(America/Kentucky/Louisville,EDT,-04:00:00,t)',),
 ('(America/Kentucky/Monticello,EDT,-04:00:00,t)',),
 ('(America/Edmonton,MDT,-06:00:00,t)',),
 ('(America/Managua,CST,-06:00:00,f)',),
 ('(America/Goose_Bay,ADT,-03:00:00,t)',),
 ('(America/St_Barthelemy,AST,-04:00:00,f)',),
 ('(America/Rainy_River,CDT,-05:00:00,t)',),
 ('(America/Panama,EST,-05:00:00,f)',),
 ('(America/Martinique,AST,-04:00:00,f)',),
 ('(America/Creston,MST,-07:00:00,f)',),
 ('(America/Santiago,-03,-03:00:00,t)',),
 ('(Hongkong,HKT,08:00:00,f)',),
 ('(ROK,KST,09:00:00,f)',),
 ('(Arctic/Longyearbyen,CET,01:00:00,f)',),
 ('(Libya,EET,02:00:00,f)',),
 ('(Portugal,WET,00:00:00,f)',),
 ('(NZ-CHAT,+1345,13:45:00,t)',),
 ('(Factory,-00,00:00:00,f)',),
 ('(Mideast/Riyadh88,zzz,03:07:04,f)',),
 ('(Mideast/Riyadh87,zzz,03:07:04,f)',),
 ('(Mideast/Riyadh89,zzz,03:07:04,f)',),
 ('(Indian/Mahe,+04,04:00:00,f)',),
 ('(Indian/Cocos,+0630,06:30:00,f)',),
 ('(Indian/Christmas,+07,07:00:00,f)',),
 ('(Indian/Mauritius,+04,04:00:00,f)',),
 ('(Indian/Chagos,+06,06:00:00,f)',),
 ('(Indian/Antananarivo,EAT,03:00:00,f)',),
 ('(Indian/Kerguelen,+05,05:00:00,f)',),
 ('(Indian/Reunion,+04,04:00:00,f)',),
 ('(Indian/Comoro,EAT,03:00:00,f)',),
 ('(Indian/Mayotte,EAT,03:00:00,f)',),
 ('(Indian/Maldives,+05,05:00:00,f)',),
 ('(UTC,UTC,00:00:00,f)',),
 ('(GMT+0,GMT,00:00:00,f)',),
 ('(WET,WET,00:00:00,f)',),
 ('(GB-Eire,GMT,00:00:00,f)',),
 ('(Mexico/General,CST,-06:00:00,f)',),
 ('(Mexico/BajaSur,MST,-07:00:00,f)',),
 ('(Mexico/BajaNorte,PDT,-07:00:00,t)',),
 ('(Antarctica/South_Pole,NZDT,13:00:00,t)',),
 ('(Antarctica/Mawson,+05,05:00:00,f)',),
 ('(Antarctica/Troll,+00,00:00:00,f)',),
 ('(Antarctica/DumontDUrville,+10,10:00:00,f)',),
 ('(Antarctica/Vostok,+06,06:00:00,f)',),
 ('(Antarctica/Syowa,+03,03:00:00,f)',),
 ('(Antarctica/Davis,+07,07:00:00,f)',),
 ('(Antarctica/McMurdo,NZDT,13:00:00,t)',),
 ('(Antarctica/Macquarie,+11,11:00:00,f)',),
 ('(Antarctica/Casey,+08,08:00:00,f)',),
 ('(Antarctica/Rothera,-03,-03:00:00,f)',),
 ('(Antarctica/Palmer,-03,-03:00:00,f)',),
 ('(Etc/GMT-6,+06,06:00:00,f)',),
 ('(Etc/GMT+8,-08,-08:00:00,f)',),
 ('(Etc/Zulu,UTC,00:00:00,f)',),
 ('(Etc/Universal,UTC,00:00:00,f)',),
 ('(Etc/UCT,UTC,00:00:00,f)',),
 ('(Etc/GMT-7,+07,07:00:00,f)',),
 ('(Etc/GMT+5,-05,-05:00:00,f)',),
 ('(Etc/GMT+9,-09,-09:00:00,f)',),
 ('(Etc/UTC,UTC,00:00:00,f)',),
 ('(Etc/GMT+0,GMT,00:00:00,f)',),
 ('(Etc/GMT+12,-12,-12:00:00,f)',),
 ('(Etc/GMT-11,+11,11:00:00,f)',),
 ('(Etc/GMT+10,-10,-10:00:00,f)',),
 ('(Etc/GMT+11,-11,-11:00:00,f)',),
 ('(Etc/Greenwich,GMT,00:00:00,f)',),
 ('(Etc/GMT-0,GMT,00:00:00,f)',),
 ('(Etc/GMT-9,+09,09:00:00,f)',),
 ('(Etc/GMT-2,+02,02:00:00,f)',),
 ('(Etc/GMT-13,+13,13:00:00,f)',),
 ('(Etc/GMT0,GMT,00:00:00,f)',),
 ('(Etc/GMT+1,-01,-01:00:00,f)',),
 ('(Etc/GMT-10,+10,10:00:00,f)',),
 ('(Etc/GMT+2,-02,-02:00:00,f)',),
 ('(Etc/GMT+7,-07,-07:00:00,f)',),
 ('(Etc/GMT-8,+08,08:00:00,f)',),
 ('(Etc/GMT-4,+04,04:00:00,f)',),
 ('(Etc/GMT-3,+03,03:00:00,f)',),
 ('(Etc/GMT+3,-03,-03:00:00,f)',),
 ('(Etc/GMT,GMT,00:00:00,f)',),
 ('(Etc/GMT+6,-06,-06:00:00,f)',),
 ('(Etc/GMT-5,+05,05:00:00,f)',),
 ('(Etc/GMT-1,+01,01:00:00,f)',),
 ('(Etc/GMT+4,-04,-04:00:00,f)',),
 ('(Etc/GMT-14,+14,14:00:00,f)',),
 ('(Etc/GMT-12,+12,12:00:00,f)',),
 ('(PRC,CST,08:00:00,f)',),
 ('(EST,EST,-05:00:00,f)',),
 ('(GB,GMT,00:00:00,f)',),
 ('(Japan,JST,09:00:00,f)',),
 ('(Singapore,+08,08:00:00,f)',),
 ('(Greenwich,GMT,00:00:00,f)',),
 ('(GMT-0,GMT,00:00:00,f)',),
 ('(EST5EDT,EDT,-04:00:00,t)',),
 ('(GMT0,GMT,00:00:00,f)',),
 ('(MET,MET,01:00:00,f)',),
 ('(Jamaica,EST,-05:00:00,f)',),
 ('(ROC,CST,08:00:00,f)',),
 ('(W-SU,MSK,03:00:00,f)',),
 ('(Poland,CET,01:00:00,f)',),
 ('(Canada/Saskatchewan,CST,-06:00:00,f)',),
 ('(Canada/Central,CDT,-05:00:00,t)',),
 ('(Canada/Yukon,PDT,-07:00:00,t)',),
 ('(Canada/Mountain,MDT,-06:00:00,t)',),
 ('(Canada/Eastern,EDT,-04:00:00,t)',),
 ('(Canada/Newfoundland,NDT,-02:30:00,t)',),
 ('(Canada/Pacific,PDT,-07:00:00,t)',),
 ('(Canada/Atlantic,ADT,-03:00:00,t)',),
 ('(GMT,GMT,00:00:00,f)',),
 ('(CET,CET,01:00:00,f)',),
 ('(Kwajalein,+12,12:00:00,f)',),
 ('(Europe/Podgorica,CET,01:00:00,f)',),
 ('(Europe/Copenhagen,CET,01:00:00,f)',),
 ('(Europe/Sofia,EET,02:00:00,f)',),
 ('(Europe/Kirov,+03,03:00:00,f)',),
 ('(Europe/Stockholm,CET,01:00:00,f)',),
 ('(Europe/Sarajevo,CET,01:00:00,f)',),
 ('(Europe/Volgograd,+04,04:00:00,f)',),
 ('(Europe/Riga,EET,02:00:00,f)',),
 ('(Europe/Brussels,CET,01:00:00,f)',),
 ('(Europe/Andorra,CET,01:00:00,f)',),
 ('(Europe/Bucharest,EET,02:00:00,f)',),
 ('(Europe/Athens,EET,02:00:00,f)',),
 ('(Europe/Vaduz,CET,01:00:00,f)',),
 ('(Europe/Busingen,CET,01:00:00,f)',),
 ('(Europe/Luxembourg,CET,01:00:00,f)',),
 ('(Europe/Tallinn,EET,02:00:00,f)',),
 ('(Europe/Monaco,CET,01:00:00,f)',),
 ('(Europe/Nicosia,EET,02:00:00,f)',),
 ('(Europe/Malta,CET,01:00:00,f)',),
 ('(Europe/Kiev,EET,02:00:00,f)',),
 ('(Europe/Amsterdam,CET,01:00:00,f)',),
 ('(Europe/Simferopol,MSK,03:00:00,f)',),
 ('(Europe/Tirane,CET,01:00:00,f)',),
 ('(Europe/Astrakhan,+04,04:00:00,f)',),
 ('(Europe/Dublin,GMT,00:00:00,t)',),
 ('(Europe/Warsaw,CET,01:00:00,f)',),
 ('(Europe/Samara,+04,04:00:00,f)',),
 ('(Europe/Madrid,CET,01:00:00,f)',),
 ('(Europe/Chisinau,EET,02:00:00,f)',),
 ('(Europe/Zaporozhye,EET,02:00:00,f)',),
 ('(Europe/Uzhgorod,EET,02:00:00,f)',),
 ('(Europe/Prague,CET,01:00:00,f)',),
 ('(Europe/Berlin,CET,01:00:00,f)',),
 ('(Europe/London,GMT,00:00:00,f)',),
 ('(Europe/Zurich,CET,01:00:00,f)',),
 ('(Europe/Vilnius,EET,02:00:00,f)',),
 ('(Europe/Ljubljana,CET,01:00:00,f)',),
 ('(Europe/Helsinki,EET,02:00:00,f)',),
 ('(Europe/Rome,CET,01:00:00,f)',),
 ('(Europe/Moscow,MSK,03:00:00,f)',),
 ('(Europe/Vienna,CET,01:00:00,f)',),
 ('(Europe/Lisbon,WET,00:00:00,f)',),
 ('(Europe/Belfast,GMT,00:00:00,f)',),
 ('(Europe/Mariehamn,EET,02:00:00,f)',),
 ('(Europe/Istanbul,+03,03:00:00,f)',),
 ('(Europe/Bratislava,CET,01:00:00,f)',),
 ('(Europe/Tiraspol,EET,02:00:00,f)',),
 ('(Europe/San_Marino,CET,01:00:00,f)',),
 ('(Europe/Zagreb,CET,01:00:00,f)',),
 ('(Europe/Ulyanovsk,+04,04:00:00,f)',),
 ('(Europe/Gibraltar,CET,01:00:00,f)',),
 ('(Europe/Isle_of_Man,GMT,00:00:00,f)',),
 ('(Europe/Jersey,GMT,00:00:00,f)',),
 ('(Europe/Saratov,+04,04:00:00,f)',),
 ('(Europe/Belgrade,CET,01:00:00,f)',),
 ('(Europe/Skopje,CET,01:00:00,f)',),
 ('(Europe/Minsk,+03,03:00:00,f)',),
 ('(Europe/Budapest,CET,01:00:00,f)',),
 ('(Europe/Kaliningrad,EET,02:00:00,f)',),
 ('(Europe/Paris,CET,01:00:00,f)',),
 ('(Europe/Vatican,CET,01:00:00,f)',),
 ('(Europe/Oslo,CET,01:00:00,f)',),
 ('(Europe/Guernsey,GMT,00:00:00,f)',),
 ('(Africa/Asmara,EAT,03:00:00,f)',),
 ('(Africa/Bujumbura,CAT,02:00:00,f)',),
 ('(Africa/Juba,EAT,03:00:00,f)',),
 ('(Africa/Lubumbashi,CAT,02:00:00,f)',),
 ('(Africa/Lagos,WAT,01:00:00,f)',),
 ('(Africa/Maputo,CAT,02:00:00,f)',),
 ('(Africa/Dakar,GMT,00:00:00,f)',),
 ('(Africa/Porto-Novo,WAT,01:00:00,f)',),
 ('(Africa/Addis_Ababa,EAT,03:00:00,f)',),
 ('(Africa/Ceuta,CET,01:00:00,f)',),
 ('(Africa/Blantyre,CAT,02:00:00,f)',),
 ('(Africa/Khartoum,CAT,02:00:00,f)',),
 ('(Africa/Djibouti,EAT,03:00:00,f)',),
 ('(Africa/Maseru,SAST,02:00:00,f)',),
 ('(Africa/Nouakchott,GMT,00:00:00,f)',),
 ('(Africa/Timbuktu,GMT,00:00:00,f)',),
 ('(Africa/Monrovia,GMT,00:00:00,f)',),
 ('(Africa/El_Aaiun,+01,01:00:00,f)',),
 ('(Africa/Bissau,GMT,00:00:00,f)',),
 ('(Africa/Niamey,WAT,01:00:00,f)',),
 ('(Africa/Kampala,EAT,03:00:00,f)',),
 ('(Africa/Luanda,WAT,01:00:00,f)',),
 ('(Africa/Conakry,GMT,00:00:00,f)',),

In [36]:
%%sql 

SELECT EXTRACT(HOUR FROM ts), COUNT(1)
FROM raw_data.session_timestamp
GROUP BY 1
ORDER BY 2 DESC

 * postgresql://gayoungjang:***@grepp-data.cduaw970ssvt.ap-northeast-2.redshift.amazonaws.com:5439/dev
24 rows affected.

[(15, 15339),
 (16, 14140),
 (14, 13417),
 (17, 10698),
 (13, 9035),
 (18, 7469),
 (19, 5278),
 (20, 3956),
 (12, 3852),
 (21, 3238),
 (22, 2801),
 (23, 2348),
 (0, 1870),
 (11, 1411),
 (1, 1328),
 (2, 1125),
 (10, 870),
 (3, 815),
 (4, 703),
 (5, 611),
 (6, 491),
 (9, 340),
 (7, 236),
 (8, 149)]

In [37]:
%%sql

SELECT EXTRACT(DOW FROM ts), COUNT(1)
FROM raw_data.session_timestamp
GROUP BY 1
ORDER BY 2 DESC

-- 0 Sun, 6 Sat

 * postgresql://gayoungjang:***@grepp-data.cduaw970ssvt.ap-northeast-2.redshift.amazonaws.com:5439/dev
7 rows affected.

[(5, 15091),
 (3, 14999),
 (4, 14901),
 (2, 14762),
 (1, 14625),
 (6, 14068),
 (0, 13074)]

Two New Tables in raw_data schema (1)
3. raw_data.session_transaction
4. raw_data.channel

In [38]:
%%sql 

SELECT *
FROM raw_data.session_transaction
LIMIT 10

 * postgresql://gayoungjang:***@grepp-data.cduaw970ssvt.ap-northeast-2.redshift.amazonaws.com:5439/dev
10 rows affected.

[('00029153d12ae1c9abe59c17ff2e0895', False, 85),
 ('008909bd27b680698322c750c400e4b1', False, 13),
 ('0107acb41ef20db2289d261d4e34fd38', False, 16),
 ('018544a2c48077d2cc3ce3278ab1e805', False, 39),
 ('020c38173caff02033564200e0288aa9', False, 61),
 ('029591145fad252b28d844d823097400', False, 13),
 ('03190309cbcd7161a426abd4782bdcd2', False, 75),
 ('03a13aa6921aed989b31d92dc73b391a', False, 129),
 ('04215c1ad3aaff3ed175446d2ea3c0f2', False, 99),
 ('049b8c570e6cc662b4a3d7e3c86e236f', False, 24)]

In [39]:
%%sql 

SELECT *
FROM raw_data.channel
LIMIT 10

 * postgresql://gayoungjang:***@grepp-data.cduaw970ssvt.ap-northeast-2.redshift.amazonaws.com:5439/dev
7 rows affected.

[('Naver',),
 ('Facebook',),
 ('Youtube',),
 ('Instagram',),
 ('TIKTOK',),
 ('Organic',),
 ('Google',)]

In [44]:
%%sql 

SELECT *
FROM raw_data.user_session_channel
LIMIT 10

 * postgresql://gayoungjang:***@grepp-data.cduaw970ssvt.ap-northeast-2.redshift.amazonaws.com:5439/dev
10 rows affected.

[(184, 'c41dd99a69df04044aa4e33ece9c9249', 'Naver'),
 (80, 'fdc0eb412a84fa549afe68373d9087e9', 'Organic'),
 (251, '0a54b19a13b6712dc04d1b49215423d8', 'Facebook'),
 (264, 'a914ecef9c12ffdb9bede64bb703d877', 'Google'),
 (744, '05ae14d7ae387b93370d142d82220f1b', 'Facebook'),
 (229, 'eddeb82df22554fa67c641e3f8a25566', 'Google'),
 (265, '4c4ea5258ef3fb3fb1fc48fee9b4408c', 'Naver'),
 (80, '8ae1da0fe37c98412768453f82490da2', 'Organic'),
 (45, '60131a2a3f223dc8f4753bcc5771660c', 'Youtube'),
 (198, '90f4760fcc9b69c13da7368c5c2917f3', 'Facebook')]

SQL 연습: raw_data.channel의 채널별 사용자수 세기

In [60]:
%%sql

SELECT A.channelname, count(DISTINCT B.userid)
FROM raw_data.channel A
LEFT JOIN raw_data.user_session_channel B ON A.channelname = B.channel
GROUP BY 1
ORDER BY 2 DESC

 * postgresql://gayoungjang:***@grepp-data.cduaw970ssvt.ap-northeast-2.redshift.amazonaws.com:5439/dev
7 rows affected.

[('Instagram', 895),
 ('Organic', 895),
 ('Google', 893),
 ('Youtube', 889),
 ('Facebook', 889),
 ('Naver', 882),
 ('TIKTOK', 0)]

SQL 연습: 사용자별로 처음 채널과 마지막 채널 알아내기 - p41

In [61]:
%%sql

SELECT ts, channel
FROM raw_data.user_session_channel usc
JOIN raw_data.session_timestamp st ON usc.sessionid = st.sessionid
WHERE userid = 251
ORDER BY 1

 * postgresql://gayoungjang:***@grepp-data.cduaw970ssvt.ap-northeast-2.redshift.amazonaws.com:5439/dev
216 rows affected.

[(datetime.datetime(2019, 5, 1, 12, 18, 26, 637000), 'Facebook'),
 (datetime.datetime(2019, 5, 2, 13, 6, 12, 47000), 'Instagram'),
 (datetime.datetime(2019, 5, 3, 13, 43, 21, 857000), 'Instagram'),
 (datetime.datetime(2019, 5, 4, 13, 54, 0, 610000), 'Instagram'),
 (datetime.datetime(2019, 5, 5, 13, 30, 8, 260000), 'Google'),
 (datetime.datetime(2019, 5, 6, 12, 36, 54, 80000), 'Youtube'),
 (datetime.datetime(2019, 5, 7, 12, 22, 45, 713000), 'Youtube'),
 (datetime.datetime(2019, 5, 8, 12, 27, 53, 360000), 'Organic'),
 (datetime.datetime(2019, 5, 9, 11, 54, 21, 527000), 'Youtube'),
 (datetime.datetime(2019, 5, 10, 14, 29, 36, 197000), 'Facebook'),
 (datetime.datetime(2019, 5, 11, 12, 42, 13, 727000), 'Facebook'),
 (datetime.datetime(2019, 5, 12, 12, 46, 57, 153000), 'Youtube'),
 (datetime.datetime(2019, 5, 13, 11, 56, 26, 650000), 'Google'),
 (datetime.datetime(2019, 5, 14, 12, 50, 53, 303000), 'Youtube'),
 (datetime.datetime(2019, 5, 15, 12, 39, 16, 610000), 'Organic'),
 (datetime.datetime(2019, 5, 16, 12, 31, 56, 140000), 'Instagram'),
 (datetime.datetime(2019, 5, 17, 13, 6, 3, 367000), 'Youtube'),
 (datetime.datetime(2019, 5, 18, 12, 32, 12, 420000), 'Youtube'),
 (datetime.datetime(2019, 5, 19, 13, 35, 51, 503000), 'Organic'),
 (datetime.datetime(2019, 5, 20, 12, 59, 25, 773000), 'Naver'),
 (datetime.datetime(2019, 5, 21, 12, 17, 36, 223000), 'Instagram'),
 (datetime.datetime(2019, 5, 21, 12, 25, 44, 910000), 'Instagram'),
 (datetime.datetime(2019, 5, 22, 12, 59, 50, 550000), 'Organic'),
 (datetime.datetime(2019, 5, 23, 12, 31, 3, 600000), 'Instagram'),
 (datetime.datetime(2019, 5, 24, 13, 15, 30, 607000), 'Naver'),
 (datetime.datetime(2019, 5, 25, 12, 46, 54, 253000), 'Facebook'),
 (datetime.datetime(2019, 5, 26, 13, 6, 16, 913000), 'Google'),
 (datetime.datetime(2019, 5, 27, 13, 15, 41, 573000), 'Youtube'),
 (datetime.datetime(2019, 5, 28, 11, 53, 17, 513000), 'Organic'),
 (datetime.datetime(2019, 5, 29, 12, 33, 2, 777000), 'Instagram'),
 (datetime.datetime(2019, 5, 30, 12, 39, 35, 553000), 'Youtube'),
 (datetime.datetime(2019, 5, 30, 17, 23, 10), 'Facebook'),
 (datetime.datetime(2019, 5, 31, 12, 18, 30, 467000), 'Youtube'),
 (datetime.datetime(2019, 6, 1, 12, 53, 38, 227000), 'Naver'),
 (datetime.datetime(2019, 6, 1, 18, 59, 41), 'Instagram'),
 (datetime.datetime(2019, 6, 2, 13, 19, 44, 780000), 'Facebook'),
 (datetime.datetime(2019, 6, 2, 15, 16, 57), 'Instagram'),
 (datetime.datetime(2019, 6, 3, 12, 29, 39, 157000), 'Google'),
 (datetime.datetime(2019, 6, 4, 13, 11, 34, 537000), 'Organic'),
 (datetime.datetime(2019, 6, 5, 12, 39, 54, 320000), 'Youtube'),
 (datetime.datetime(2019, 6, 6, 12, 35, 31, 260000), 'Instagram'),
 (datetime.datetime(2019, 6, 7, 14, 13, 30, 970000), 'Google'),
 (datetime.datetime(2019, 6, 8, 12, 58, 44, 550000), 'Organic'),
 (datetime.datetime(2019, 6, 9, 12, 58, 28, 37000), 'Naver'),
 (datetime.datetime(2019, 6, 10, 13, 0, 17, 77000), 'Instagram'),
 (datetime.datetime(2019, 6, 10, 15, 2, 56, 180000), 'Instagram'),
 (datetime.datetime(2019, 6, 11, 13, 35, 18, 527000), 'Google'),
 (datetime.datetime(2019, 6, 12, 13, 13, 36, 663000), 'Organic'),
 (datetime.datetime(2019, 6, 13, 13, 31, 34, 237000), 'Organic'),
 (datetime.datetime(2019, 6, 14, 13, 19, 42, 297000), 'Organic'),
 (datetime.datetime(2019, 6, 14, 13, 24, 3, 453000), 'Youtube'),
 (datetime.datetime(2019, 6, 15, 13, 7, 3, 207000), 'Instagram'),
 (datetime.datetime(2019, 6, 16, 12, 44, 44, 787000), 'Google'),
 (datetime.datetime(2019, 6, 17, 13, 13, 3, 103000), 'Instagram'),
 (datetime.datetime(2019, 6, 18, 12, 33, 17, 483000), 'Instagram'),
 (datetime.datetime(2019, 6, 19, 12, 38, 26, 733000), 'Instagram'),
 (datetime.datetime(2019, 6, 20, 12, 50, 39, 390000), 'Youtube'),
 (datetime.datetime(2019, 6, 21, 12, 57, 52, 737000), 'Naver'),
 (datetime.datetime(2019, 6, 22, 13, 21, 12, 57000), 'Naver'),
 (datetime.datetime(2019, 6, 22, 16, 4, 40), 'Naver'),
 (datetime.datetime(2019, 6, 23, 12, 33, 2, 350000), 'Facebook'),
 (datetime.datetime(2019, 6, 24, 12, 20, 55, 627000), 'Naver'),
 (datetime.datetime(2019, 6, 25, 12, 53, 30, 443000), 'Organic'),
 (datetime.datetime(2019, 6, 26, 12, 16, 51, 993000), 'Facebook'),
 (datetime.datetime(2019, 6, 26, 18, 36, 54), 'Facebook'),
 (datetime.datetime(2019, 6, 27, 13, 50, 9, 650000), 'Google'),
 (datetime.datetime(2019, 6, 28, 13, 15, 23, 967000), 'Youtube'),
 (datetime.datetime(2019, 6, 29, 13, 38, 34, 300000), 'Instagram'),
 (datetime.datetime(2019, 6, 29, 13, 42, 47, 183000), 'Google'),
 (datetime.datetime(2019, 6, 29, 13, 43, 52, 563000), 'Google'),
 (datetime.datetime(2019, 6, 30, 12, 45, 5, 493000), 'Organic'),
 (datetime.datetime(2019, 7, 1, 12, 27, 32, 790000), 'Instagram'),
 (datetime.datetime(2019, 7, 1, 17, 58, 15), 'Instagram'),
 (datetime.datetime(2019, 7, 2, 13, 19, 33, 543000), 'Facebook'),
 (datetime.datetime(2019, 7, 2, 14, 56, 39, 963000), 'Organic'),
 (datetime.datetime(2019, 7, 3, 12, 48, 27, 257000), 'Organic'),
 (datetime.datetime(2019, 7, 8, 12, 53, 49, 693000), 'Organic'),
 (datetime.datetime(2019, 7, 9, 12, 21, 37, 27000), 'Organic'),
 (datetime.datetime(2019, 7, 10, 12, 41, 56, 653000), 'Instagram'),
 (datetime.datetime(2019, 7, 11, 13, 2, 33, 940000), 'Youtube'),
 (datetime.datetime(2019, 7, 12, 12, 39, 45, 390000), 'Naver'),
 (datetime.datetime(2019, 7, 13, 13, 16, 19, 803000), 'Youtube'),
 (datetime.datetime(2019, 7, 13, 13, 19, 5, 797000), 'Youtube'),
 (datetime.datetime(2019, 7, 14, 14, 34, 33, 657000), 'Youtube'),
 (datetime.datetime(2019, 7, 17, 12, 44, 32, 63000), 'Organic'),
 (datetime.datetime(2019, 7, 17, 16, 53, 22), 'Google'),
 (datetime.datetime(2019, 7, 18, 12, 51, 54, 643000), 'Youtube'),
 (datetime.datetime(2019, 7, 18, 12, 56, 43, 577000), 'Youtube'),
 (datetime.datetime(2019, 7, 18, 20, 29, 57), 'Youtube'),
 (datetime.datetime(2019, 7, 19, 16, 1, 16, 17000), 'Naver'),
 (datetime.datetime(2019, 7, 19, 17, 38, 53), 'Organic'),
 (datetime.datetime(2019, 7, 19, 17, 40, 18), 'Instagram'),
 (datetime.datetime(2019, 7, 19, 17, 41, 51), 'Instagram'),
 (datetime.datetime(2019, 7, 19, 17, 43, 51), 'Youtube'),
 (datetime.datetime(2019, 7, 20, 12, 57, 48, 747000), 'Naver'),
 (datetime.datetime(2019, 7, 20, 13, 1, 13, 857000), 'Instagram'),
 (datetime.datetime(2019, 7, 21, 12, 53, 14, 990000), 'Instagram'),
 (datetime.datetime(2019, 7, 22, 13, 19, 23, 447000), 'Youtube'),
 (datetime.datetime(2019, 7, 23, 12, 47, 7, 460000), 'Naver'),
 (datetime.datetime(2019, 7, 24, 12, 54, 51, 497000), 'Google'),
 (datetime.datetime(2019, 7, 24, 16, 8, 42), 'Google'),
 (datetime.datetime(2019, 7, 25, 12, 34, 51, 103000), 'Instagram'),
 (datetime.datetime(2019, 7, 25, 12, 39, 35, 593000), 'Instagram'),
 (datetime.datetime(2019, 7, 26, 12, 47, 35, 500000), 'Instagram'),
 (datetime.datetime(2019, 7, 26, 12, 52, 22, 50000), 'Organic'),
 (datetime.datetime(2019, 7, 26, 19, 18, 38), 'Google'),
 (datetime.datetime(2019, 7, 27, 13, 33, 2, 323000), 'Google'),
 (datetime.datetime(2019, 7, 29, 13, 6, 27, 130000), 'Facebook'),
 (datetime.datetime(2019, 7, 30, 12, 23, 24, 593000), 'Google'),
 (datetime.datetime(2019, 7, 30, 15, 31, 25), 'Instagram'),
 (datetime.datetime(2019, 7, 31, 13, 38, 48, 527000), 'Facebook'),
 (datetime.datetime(2019, 8, 1, 12, 56, 52, 543000), 'Google'),
 (datetime.datetime(2019, 8, 2, 13, 32, 39, 743000), 'Naver'),
 (datetime.datetime(2019, 8, 3, 14, 2, 1, 400000), 'Youtube'),
 (datetime.datetime(2019, 8, 4, 13, 53, 54, 553000), 'Instagram'),
 (datetime.datetime(2019, 8, 5, 12, 37, 58, 720000), 'Organic'),
 (datetime.datetime(2019, 8, 6, 12, 47, 42, 17000), 'Youtube'),
 (datetime.datetime(2019, 8, 7, 12, 42, 7, 713000), 'Facebook'),
 (datetime.datetime(2019, 8, 8, 12, 7, 18, 430000), 'Instagram'),
 (datetime.datetime(2019, 8, 9, 13, 19, 19, 580000), 'Organic'),
 (datetime.datetime(2019, 8, 10, 14, 3, 46, 323000), 'Organic'),
 (datetime.datetime(2019, 8, 11, 13, 57, 58, 377000), 'Naver'),
 (datetime.datetime(2019, 8, 12, 12, 46, 55, 367000), 'Instagram'),
 (datetime.datetime(2019, 8, 13, 12, 22, 28, 127000), 'Instagram'),
 (datetime.datetime(2019, 8, 14, 12, 10, 21, 790000), 'Instagram'),
 (datetime.datetime(2019, 8, 15, 17, 28, 48, 497000), 'Naver'),
 (datetime.datetime(2019, 8, 16, 13, 54, 53, 113000), 'Instagram'),
 (datetime.datetime(2019, 8, 17, 14, 11, 54, 877000), 'Instagram'),
 (datetime.datetime(2019, 8, 18, 13, 38, 14, 420000), 'Organic'),
 (datetime.datetime(2019, 8, 19, 13, 24, 12, 170000), 'Youtube'),
 (datetime.datetime(2019, 8, 20, 13, 33, 0, 347000), 'Facebook'),
 (datetime.datetime(2019, 8, 21, 13, 34, 23, 947000), 'Facebook'),
 (datetime.datetime(2019, 8, 21, 13, 37, 4, 953000), 'Google'),
 (datetime.datetime(2019, 8, 22, 12, 36, 23, 127000), 'Google'),
 (datetime.datetime(2019, 8, 23, 14, 0, 1, 60000), 'Facebook'),
 (datetime.datetime(2019, 8, 25, 14, 58, 40, 387000), 'Organic'),
 (datetime.datetime(2019, 8, 26, 13, 41, 51, 137000), 'Naver'),
 (datetime.datetime(2019, 8, 27, 12, 21, 19, 190000), 'Naver'),
 (datetime.datetime(2019, 8, 28, 13, 2, 15, 903000), 'Naver'),
 (datetime.datetime(2019, 8, 28, 13, 4, 53, 717000), 'Youtube'),
 (datetime.datetime(2019, 8, 29, 12, 17, 3, 380000), 'Organic'),
 (datetime.datetime(2019, 9, 3, 14, 46, 40, 353000), 'Organic'),
 (datetime.datetime(2019, 9, 3, 16, 11, 29), 'Facebook'),
 (datetime.datetime(2019, 9, 3, 16, 12, 24), 'Google'),
 (datetime.datetime(2019, 9, 4, 12, 59, 13, 917000), 'Naver'),
 (datetime.datetime(2019, 9, 5, 12, 35, 33, 793000), 'Facebook'),
 (datetime.datetime(2019, 9, 6, 13, 29, 40, 160000), 'Instagram'),
 (datetime.datetime(2019, 9, 6, 18, 53, 41, 373000), 'Google'),
 (datetime.datetime(2019, 9, 7, 14, 50, 41, 860000), 'Instagram'),
 (datetime.datetime(2019, 9, 8, 13, 44, 0, 730000), 'Instagram'),
 (datetime.datetime(2019, 9, 9, 12, 30, 40, 303000), 'Naver'),
 (datetime.datetime(2019, 9, 10, 12, 56, 17, 543000), 'Facebook'),
 (datetime.datetime(2019, 9, 11, 13, 9, 50, 40000), 'Google'),
 (datetime.datetime(2019, 9, 12, 13, 34, 36, 337000), 'Facebook'),
 (datetime.datetime(2019, 9, 13, 13, 18, 58, 977000), 'Instagram'),
 (datetime.datetime(2019, 9, 14, 13, 43, 47, 3000), 'Naver'),
 (datetime.datetime(2019, 9, 15, 13, 40, 54, 840000), 'Organic'),
 (datetime.datetime(2019, 9, 16, 13, 39, 13, 283000), 'Organic'),
 (datetime.datetime(2019, 9, 17, 12, 23, 56, 137000), 'Youtube'),
 (datetime.datetime(2019, 9, 18, 13, 37, 0, 210000), 'Naver'),
 (datetime.datetime(2019, 9, 19, 13, 51, 55, 193000), 'Organic'),
 (datetime.datetime(2019, 9, 20, 13, 52, 45, 850000), 'Naver'),
 (datetime.datetime(2019, 9, 22, 14, 41, 19, 317000), 'Facebook'),
 (datetime.datetime(2019, 9, 23, 12, 43, 30, 643000), 'Organic'),
 (datetime.datetime(2019, 9, 24, 15, 4, 54, 267000), 'Instagram'),
 (datetime.datetime(2019, 9, 25, 13, 29, 38, 347000), 'Instagram'),
 (datetime.datetime(2019, 9, 27, 13, 13, 26, 970000), 'Organic'),
 (datetime.datetime(2019, 9, 29, 14, 1, 37, 303000), 'Instagram'),
 (datetime.datetime(2019, 9, 30, 13, 30, 34, 823000), 'Naver'),
 (datetime.datetime(2019, 10, 2, 14, 51, 24, 390000), 'Youtube'),
 (datetime.datetime(2019, 10, 3, 14, 57, 24, 417000), 'Organic'),
 (datetime.datetime(2019, 10, 3, 18, 15, 4, 250000), 'Instagram'),
 (datetime.datetime(2019, 10, 3, 19, 56, 38), 'Youtube'),
 (datetime.datetime(2019, 10, 4, 15, 31, 35, 587000), 'Youtube'),
 (datetime.datetime(2019, 10, 5, 15, 6, 28, 717000), 'Youtube'),
 (datetime.datetime(2019, 10, 7, 13, 0, 30, 950000), 'Naver'),
 (datetime.datetime(2019, 10, 8, 12, 52, 10, 823000), 'Instagram'),
 (datetime.datetime(2019, 10, 9, 14, 13, 5, 130000), 'Instagram'),
 (datetime.datetime(2019, 10, 13, 15, 57, 9, 387000), 'Naver'),
 (datetime.datetime(2019, 10, 14, 17, 7, 54, 133000), 'Google'),
 (datetime.datetime(2019, 10, 15, 12, 57, 35, 127000), 'Instagram'),
 (datetime.datetime(2019, 10, 16, 14, 1, 36, 993000), 'Instagram'),
 (datetime.datetime(2019, 10, 17, 12, 35, 49, 640000), 'Google'),
 (datetime.datetime(2019, 10, 18, 14, 29, 12, 150000), 'Instagram'),
 (datetime.datetime(2019, 10, 20, 14, 23, 12, 523000), 'Youtube'),
 (datetime.datetime(2019, 10, 21, 13, 6, 43, 27000), 'Naver'),
 (datetime.datetime(2019, 10, 22, 13, 21, 42, 390000), 'Organic'),
 (datetime.datetime(2019, 10, 23, 13, 42, 59, 783000), 'Youtube'),
 (datetime.datetime(2019, 10, 23, 20, 16, 21), 'Youtube'),
 (datetime.datetime(2019, 10, 24, 13, 19, 58, 673000), 'Google'),
 (datetime.datetime(2019, 10, 27, 12, 55, 38, 563000), 'Instagram'),
 (datetime.datetime(2019, 10, 28, 15, 23, 22, 480000), 'Google'),
 (datetime.datetime(2019, 10, 29, 13, 41, 50, 303000), 'Naver'),
 (datetime.datetime(2019, 10, 29, 13, 42, 40, 357000), 'Naver'),
 (datetime.datetime(2019, 10, 29, 13, 47, 47, 353000), 'Facebook'),
 (datetime.datetime(2019, 10, 30, 15, 56, 53, 263000), 'Youtube'),
 (datetime.datetime(2019, 10, 31, 13, 59, 2, 907000), 'Naver'),
 (datetime.datetime(2019, 11, 5, 16, 29, 17, 403000), 'Youtube'),
 (datetime.datetime(2019, 11, 6, 13, 12, 22, 887000), 'Organic'),
 (datetime.datetime(2019, 11, 7, 14, 13, 54, 197000), 'Organic'),
 (datetime.datetime(2019, 11, 8, 14, 52, 52, 620000), 'Youtube'),
 (datetime.datetime(2019, 11, 8, 14, 56, 39, 267000), 'Youtube'),
 (datetime.datetime(2019, 11, 9, 15, 23, 15, 843000), 'Youtube'),
 (datetime.datetime(2019, 11, 10, 15, 49, 40, 190000), 'Organic'),
 (datetime.datetime(2019, 11, 11, 14, 7, 44, 547000), 'Instagram'),
 (datetime.datetime(2019, 11, 14, 15, 33, 8, 933000), 'Google'),
 (datetime.datetime(2019, 11, 14, 15, 38, 15, 263000), 'Organic'),
 (datetime.datetime(2019, 11, 17, 14, 36, 52), 'Youtube'),
 (datetime.datetime(2019, 11, 18, 16, 24, 2), 'Facebook'),
 (datetime.datetime(2019, 11, 19, 16, 28, 12), 'Youtube'),
 (datetime.datetime(2019, 11, 20, 15, 41, 25), 'Google'),
 (datetime.datetime(2019, 11, 21, 15, 44, 1), 'Naver'),
 (datetime.datetime(2019, 11, 22, 17, 55, 35), 'Facebook'),
 (datetime.datetime(2019, 11, 23, 15, 34, 30), 'Google'),
 (datetime.datetime(2019, 11, 25, 14, 31, 24), 'Organic'),
 (datetime.datetime(2019, 11, 26, 16, 54, 19), 'Google')]

In [62]:
%%sql

 SELECT *, ROW_NUMBER() OVER (PARTITION BY userid  ORDER BY st.ts) as rnum
 FROM raw_data.user_session_channel usc
 JOIN raw_data.session_timestamp st ON usc.sessionid = st.sessionid
 WHERE userid = 251

 * postgresql://gayoungjang:***@grepp-data.cduaw970ssvt.ap-northeast-2.redshift.amazonaws.com:5439/dev
216 rows affected.

[(251, '0a54b19a13b6712dc04d1b49215423d8', 'Facebook', '0a54b19a13b6712dc04d1b49215423d8', datetime.datetime(2019, 5, 1, 12, 18, 26, 637000), 1),
 (251, 'fe45e3227f3805b1314414203c4e5206', 'Instagram', 'fe45e3227f3805b1314414203c4e5206', datetime.datetime(2019, 5, 2, 13, 6, 12, 47000), 2),
 (251, 'f4e3ce3e7b581ff32e40968298ba013d', 'Instagram', 'f4e3ce3e7b581ff32e40968298ba013d', datetime.datetime(2019, 5, 3, 13, 43, 21, 857000), 3),
 (251, '436db71e03605b5aea1e08078f29f7f2', 'Instagram', '436db71e03605b5aea1e08078f29f7f2', datetime.datetime(2019, 5, 4, 13, 54, 0, 610000), 4),
 (251, '033cc385728c51d97360020ed57776f0', 'Google', '033cc385728c51d97360020ed57776f0', datetime.datetime(2019, 5, 5, 13, 30, 8, 260000), 5),
 (251, '8ce8b102d40392a688f8c04b3cd6cae0', 'Youtube', '8ce8b102d40392a688f8c04b3cd6cae0', datetime.datetime(2019, 5, 6, 12, 36, 54, 80000), 6),
 (251, '44ece762ae7e41e3a0b1301488907eaa', 'Youtube', '44ece762ae7e41e3a0b1301488907eaa', datetime.datetime(2019, 5, 7, 12, 22, 45, 713000), 7),
 (251, 'b47767f992ce8624345aca182b76b202', 'Organic', 'b47767f992ce8624345aca182b76b202', datetime.datetime(2019, 5, 8, 12, 27, 53, 360000), 8),
 (251, '23937b42f9273974570fb5a56a6652ee', 'Youtube', '23937b42f9273974570fb5a56a6652ee', datetime.datetime(2019, 5, 9, 11, 54, 21, 527000), 9),
 (251, 'a7b23e6eefbe6cf04b8e62a6f0915550', 'Facebook', 'a7b23e6eefbe6cf04b8e62a6f0915550', datetime.datetime(2019, 5, 10, 14, 29, 36, 197000), 10),
 (251, 'ff42b03a06a1bed4e936f0e04958e168', 'Facebook', 'ff42b03a06a1bed4e936f0e04958e168', datetime.datetime(2019, 5, 11, 12, 42, 13, 727000), 11),
 (251, '85c4ef2f7a943600c97b5903247567b7', 'Youtube', '85c4ef2f7a943600c97b5903247567b7', datetime.datetime(2019, 5, 12, 12, 46, 57, 153000), 12),
 (251, '21c3134ee5edcb618c4f9aae358d73a7', 'Google', '21c3134ee5edcb618c4f9aae358d73a7', datetime.datetime(2019, 5, 13, 11, 56, 26, 650000), 13),
 (251, '85dfba75bcadb576723264b5986f2ac2', 'Youtube', '85dfba75bcadb576723264b5986f2ac2', datetime.datetime(2019, 5, 14, 12, 50, 53, 303000), 14),
 (251, '0a93091da5efb0d9d5649e7f6b2ad9d7', 'Organic', '0a93091da5efb0d9d5649e7f6b2ad9d7', datetime.datetime(2019, 5, 15, 12, 39, 16, 610000), 15),
 (251, '7658d0dd31ff8ec12a3933f064e000a1', 'Instagram', '7658d0dd31ff8ec12a3933f064e000a1', datetime.datetime(2019, 5, 16, 12, 31, 56, 140000), 16),
 (251, 'c47eedbcf5a800ee4216797e5665eb21', 'Youtube', 'c47eedbcf5a800ee4216797e5665eb21', datetime.datetime(2019, 5, 17, 13, 6, 3, 367000), 17),
 (251, 'adb0e2c465ae2a4b7698a8901fdbb177', 'Youtube', 'adb0e2c465ae2a4b7698a8901fdbb177', datetime.datetime(2019, 5, 18, 12, 32, 12, 420000), 18),
 (251, '74c4481c34e417ac39d1de6b4f854c4f', 'Organic', '74c4481c34e417ac39d1de6b4f854c4f', datetime.datetime(2019, 5, 19, 13, 35, 51, 503000), 19),
 (251, '5df0385cba256a135be596dbe28fa7aa', 'Naver', '5df0385cba256a135be596dbe28fa7aa', datetime.datetime(2019, 5, 20, 12, 59, 25, 773000), 20),
 (251, '1eaa260fddcc15e3c1f09453b8d5bd92', 'Instagram', '1eaa260fddcc15e3c1f09453b8d5bd92', datetime.datetime(2019, 5, 21, 12, 17, 36, 223000), 21),
 (251, '82d3149fc1f8d2305e7c6d56a6c5689d', 'Instagram', '82d3149fc1f8d2305e7c6d56a6c5689d', datetime.datetime(2019, 5, 21, 12, 25, 44, 910000), 22),
 (251, '5c5bc7df3d37b2a7ea29e1b47b2bd4ab', 'Organic', '5c5bc7df3d37b2a7ea29e1b47b2bd4ab', datetime.datetime(2019, 5, 22, 12, 59, 50, 550000), 23),
 (251, '35675fd71a153bf3baab29b904e525c8', 'Instagram', '35675fd71a153bf3baab29b904e525c8', datetime.datetime(2019, 5, 23, 12, 31, 3, 600000), 24),
 (251, 'c0a0756dd0a93eb7c840fdeb3c65808e', 'Naver', 'c0a0756dd0a93eb7c840fdeb3c65808e', datetime.datetime(2019, 5, 24, 13, 15, 30, 607000), 25),
 (251, '7d90ca24dfbc4ba4465647f0cd89c245', 'Facebook', '7d90ca24dfbc4ba4465647f0cd89c245', datetime.datetime(2019, 5, 25, 12, 46, 54, 253000), 26),
 (251, '44c74289986156fe463934320cf9444e', 'Google', '44c74289986156fe463934320cf9444e', datetime.datetime(2019, 5, 26, 13, 6, 16, 913000), 27),
 (251, '0bcd25b83e703478c74c9f575039f3f1', 'Youtube', '0bcd25b83e703478c74c9f575039f3f1', datetime.datetime(2019, 5, 27, 13, 15, 41, 573000), 28),
 (251, 'ddfa8a1fa86914072eb6e3e55c253856', 'Organic', 'ddfa8a1fa86914072eb6e3e55c253856', datetime.datetime(2019, 5, 28, 11, 53, 17, 513000), 29),
 (251, 'fac9f8fdf66019365db95e4c1edef2bc', 'Instagram', 'fac9f8fdf66019365db95e4c1edef2bc', datetime.datetime(2019, 5, 29, 12, 33, 2, 777000), 30),
 (251, 'b92f8ab7a47e21fb033068842d6663b0', 'Youtube', 'b92f8ab7a47e21fb033068842d6663b0', datetime.datetime(2019, 5, 30, 12, 39, 35, 553000), 31),
 (251, 'da8a2ad589abfa0892e6284b879d7b7d', 'Facebook', 'da8a2ad589abfa0892e6284b879d7b7d', datetime.datetime(2019, 5, 30, 17, 23, 10), 32),
 (251, '723e8f97fde15f7a8d5ff8d558ea3f16', 'Youtube', '723e8f97fde15f7a8d5ff8d558ea3f16', datetime.datetime(2019, 5, 31, 12, 18, 30, 467000), 33),
 (251, 'bf15e9bbff22c7719020f9df4badc20a', 'Naver', 'bf15e9bbff22c7719020f9df4badc20a', datetime.datetime(2019, 6, 1, 12, 53, 38, 227000), 34),
 (251, 'bcb74281f42b1d3a4c6790fa159876ba', 'Instagram', 'bcb74281f42b1d3a4c6790fa159876ba', datetime.datetime(2019, 6, 1, 18, 59, 41), 35),
 (251, '89f3c33175c57115408f4fd8a8557751', 'Facebook', '89f3c33175c57115408f4fd8a8557751', datetime.datetime(2019, 6, 2, 13, 19, 44, 780000), 36),
 (251, 'd8c1d317721776ba9d38a3cccd33a79a', 'Instagram', 'd8c1d317721776ba9d38a3cccd33a79a', datetime.datetime(2019, 6, 2, 15, 16, 57), 37),
 (251, 'd0e7244b36e4e2cfcc04d247bff16291', 'Google', 'd0e7244b36e4e2cfcc04d247bff16291', datetime.datetime(2019, 6, 3, 12, 29, 39, 157000), 38),
 (251, '54591b5c8d4291c395119bdbdb3a4ee9', 'Organic', '54591b5c8d4291c395119bdbdb3a4ee9', datetime.datetime(2019, 6, 4, 13, 11, 34, 537000), 39),
 (251, '159a09c517c606c8d96a6b18c6e2e4d9', 'Youtube', '159a09c517c606c8d96a6b18c6e2e4d9', datetime.datetime(2019, 6, 5, 12, 39, 54, 320000), 40),
 (251, '0af62754d41faf4cabd69b68b2d0368f', 'Instagram', '0af62754d41faf4cabd69b68b2d0368f', datetime.datetime(2019, 6, 6, 12, 35, 31, 260000), 41),
 (251, 'e775a20f0553c08010a113c9c67de544', 'Google', 'e775a20f0553c08010a113c9c67de544', datetime.datetime(2019, 6, 7, 14, 13, 30, 970000), 42),
 (251, '2e0a791950a53842e60d83295368cdff', 'Organic', '2e0a791950a53842e60d83295368cdff', datetime.datetime(2019, 6, 8, 12, 58, 44, 550000), 43),
 (251, 'b54a39e62236c79ee0536b932f6e76b3', 'Naver', 'b54a39e62236c79ee0536b932f6e76b3', datetime.datetime(2019, 6, 9, 12, 58, 28, 37000), 44),
 (251, '8d8875e24e23d69f253a077f447ed7c3', 'Instagram', '8d8875e24e23d69f253a077f447ed7c3', datetime.datetime(2019, 6, 10, 13, 0, 17, 77000), 45),
 (251, 'd8d3a2d972d6cb50e983baa5673ea92a', 'Instagram', 'd8d3a2d972d6cb50e983baa5673ea92a', datetime.datetime(2019, 6, 10, 15, 2, 56, 180000), 46),
 (251, 'a80ff02f8227904e65413f89ee1719e6', 'Google', 'a80ff02f8227904e65413f89ee1719e6', datetime.datetime(2019, 6, 11, 13, 35, 18, 527000), 47),
 (251, 'e15c78fe25d60a659d23e62645fa1a2d', 'Organic', 'e15c78fe25d60a659d23e62645fa1a2d', datetime.datetime(2019, 6, 12, 13, 13, 36, 663000), 48),
 (251, '8248f16fa738b0bfe6013edf69d873bf', 'Organic', '8248f16fa738b0bfe6013edf69d873bf', datetime.datetime(2019, 6, 13, 13, 31, 34, 237000), 49),
 (251, '735475d64a23bbf3e94a5c49c5749349', 'Organic', '735475d64a23bbf3e94a5c49c5749349', datetime.datetime(2019, 6, 14, 13, 19, 42, 297000), 50),
 (251, '8576d5a526fe75112fee46cc3a77e927', 'Youtube', '8576d5a526fe75112fee46cc3a77e927', datetime.datetime(2019, 6, 14, 13, 24, 3, 453000), 51),
 (251, '881e945c3b5ccf17103ecca2b675585f', 'Instagram', '881e945c3b5ccf17103ecca2b675585f', datetime.datetime(2019, 6, 15, 13, 7, 3, 207000), 52),
 (251, 'd3db718a011f94f39dd49b576d785b08', 'Google', 'd3db718a011f94f39dd49b576d785b08', datetime.datetime(2019, 6, 16, 12, 44, 44, 787000), 53),
 (251, '60b8b65c7b7342a9caa07a07aea0ccac', 'Instagram', '60b8b65c7b7342a9caa07a07aea0ccac', datetime.datetime(2019, 6, 17, 13, 13, 3, 103000), 54),
 (251, 'f30daccec8daeda7e4adba492c474276', 'Instagram', 'f30daccec8daeda7e4adba492c474276', datetime.datetime(2019, 6, 18, 12, 33, 17, 483000), 55),
 (251, '4d8d751988a68fec6e98d0a65284f530', 'Instagram', '4d8d751988a68fec6e98d0a65284f530', datetime.datetime(2019, 6, 19, 12, 38, 26, 733000), 56),
 (251, 'a91edecd508cd9e5b3049e1918f0c6eb', 'Youtube', 'a91edecd508cd9e5b3049e1918f0c6eb', datetime.datetime(2019, 6, 20, 12, 50, 39, 390000), 57),
 (251, '4839aef58602c3debaf41ef02dd2ae15', 'Naver', '4839aef58602c3debaf41ef02dd2ae15', datetime.datetime(2019, 6, 21, 12, 57, 52, 737000), 58),
 (251, '8e0421004941cba9a3a903e2443cae69', 'Naver', '8e0421004941cba9a3a903e2443cae69', datetime.datetime(2019, 6, 22, 13, 21, 12, 57000), 59),
 (251, '6a9a797ccb892a524ae64718347d74ce', 'Naver', '6a9a797ccb892a524ae64718347d74ce', datetime.datetime(2019, 6, 22, 16, 4, 40), 60),
 (251, 'ae4f3688990e2b80925aa342627625e7', 'Facebook', 'ae4f3688990e2b80925aa342627625e7', datetime.datetime(2019, 6, 23, 12, 33, 2, 350000), 61),
 (251, 'aed56e569b6d56dc436e9c9d9bce42dd', 'Naver', 'aed56e569b6d56dc436e9c9d9bce42dd', datetime.datetime(2019, 6, 24, 12, 20, 55, 627000), 62),
 (251, '2e109050f2fc63b816c101dfb8827600', 'Organic', '2e109050f2fc63b816c101dfb8827600', datetime.datetime(2019, 6, 25, 12, 53, 30, 443000), 63),
 (251, '398e24b46129ded49457c65ce367eab7', 'Facebook', '398e24b46129ded49457c65ce367eab7', datetime.datetime(2019, 6, 26, 12, 16, 51, 993000), 64),
 (251, 'ecb78e3b1dd950b9621f548bcc02dbe9', 'Facebook', 'ecb78e3b1dd950b9621f548bcc02dbe9', datetime.datetime(2019, 6, 26, 18, 36, 54), 65),
 (251, 'fbfdab7e3983009e7d488d946a8de066', 'Google', 'fbfdab7e3983009e7d488d946a8de066', datetime.datetime(2019, 6, 27, 13, 50, 9, 650000), 66),
 (251, 'f314e8e9133de8ef063cb1518b4bffcb', 'Youtube', 'f314e8e9133de8ef063cb1518b4bffcb', datetime.datetime(2019, 6, 28, 13, 15, 23, 967000), 67),
 (251, '29d1165b61ef7dc62cecf00ea22b1d93', 'Instagram', '29d1165b61ef7dc62cecf00ea22b1d93', datetime.datetime(2019, 6, 29, 13, 38, 34, 300000), 68),
 (251, '50d944a1f44b855a5144c17e8fc33973', 'Google', '50d944a1f44b855a5144c17e8fc33973', datetime.datetime(2019, 6, 29, 13, 42, 47, 183000), 69),
 (251, '7adf7e3474d1857cc588cefbc4d68f55', 'Google', '7adf7e3474d1857cc588cefbc4d68f55', datetime.datetime(2019, 6, 29, 13, 43, 52, 563000), 70),
 (251, '9f727bc55d5aa9dc9349ea9da97b1ff8', 'Organic', '9f727bc55d5aa9dc9349ea9da97b1ff8', datetime.datetime(2019, 6, 30, 12, 45, 5, 493000), 71),
 (251, '8132c4bd0e503a33e9f5139f216d4c82', 'Instagram', '8132c4bd0e503a33e9f5139f216d4c82', datetime.datetime(2019, 7, 1, 12, 27, 32, 790000), 72),
 (251, 'c209163f3e310b6c0a9a2c6489e22a8e', 'Instagram', 'c209163f3e310b6c0a9a2c6489e22a8e', datetime.datetime(2019, 7, 1, 17, 58, 15), 73),
 (251, 'e96822f795a48a236359926ee499b783', 'Facebook', 'e96822f795a48a236359926ee499b783', datetime.datetime(2019, 7, 2, 13, 19, 33, 543000), 74),
 (251, '6c7a9f7314e184c928cd9fd0efd3b659', 'Organic', '6c7a9f7314e184c928cd9fd0efd3b659', datetime.datetime(2019, 7, 2, 14, 56, 39, 963000), 75),
 (251, 'db31e0a485a2b6c73be7067dd95c0c5e', 'Organic', 'db31e0a485a2b6c73be7067dd95c0c5e', datetime.datetime(2019, 7, 3, 12, 48, 27, 257000), 76),
 (251, '4ede9640e357f086a55ab84467f2bfe2', 'Organic', '4ede9640e357f086a55ab84467f2bfe2', datetime.datetime(2019, 7, 8, 12, 53, 49, 693000), 77),
 (251, '83870fb92477054676ffda84e1e22f9f', 'Organic', '83870fb92477054676ffda84e1e22f9f', datetime.datetime(2019, 7, 9, 12, 21, 37, 27000), 78),
 (251, 'd48fff99ca7aafcfe2e7a5c530eef864', 'Instagram', 'd48fff99ca7aafcfe2e7a5c530eef864', datetime.datetime(2019, 7, 10, 12, 41, 56, 653000), 79),
 (251, 'ce4e66f7f29c8b37eff635378a9b9c0f', 'Youtube', 'ce4e66f7f29c8b37eff635378a9b9c0f', datetime.datetime(2019, 7, 11, 13, 2, 33, 940000), 80),
 (251, '3995fe50d83f15ea0930e355f452de8d', 'Naver', '3995fe50d83f15ea0930e355f452de8d', datetime.datetime(2019, 7, 12, 12, 39, 45, 390000), 81),
 (251, '4eedf3f92629bc3b1a208cfaacc4b2d2', 'Youtube', '4eedf3f92629bc3b1a208cfaacc4b2d2', datetime.datetime(2019, 7, 13, 13, 16, 19, 803000), 82),
 (251, '7faf67c63084cf8345243e912885f1a5', 'Youtube', '7faf67c63084cf8345243e912885f1a5', datetime.datetime(2019, 7, 13, 13, 19, 5, 797000), 83),
 (251, '7b4436d7d402f3a6b9a11d6ca58c4057', 'Youtube', '7b4436d7d402f3a6b9a11d6ca58c4057', datetime.datetime(2019, 7, 14, 14, 34, 33, 657000), 84),
 (251, '756b48358bcdecd7f25216f4fb2a4e13', 'Organic', '756b48358bcdecd7f25216f4fb2a4e13', datetime.datetime(2019, 7, 17, 12, 44, 32, 63000), 85),
 (251, 'd82815d548d98ff14d95120eef2e6a3c', 'Google', 'd82815d548d98ff14d95120eef2e6a3c', datetime.datetime(2019, 7, 17, 16, 53, 22), 86),
 (251, 'da97c8240e2ad99a2d331eed95c411f5', 'Youtube', 'da97c8240e2ad99a2d331eed95c411f5', datetime.datetime(2019, 7, 18, 12, 51, 54, 643000), 87),
 (251, '159f02cdca45838bdfe5ecdeadb520be', 'Youtube', '159f02cdca45838bdfe5ecdeadb520be', datetime.datetime(2019, 7, 18, 12, 56, 43, 577000), 88),
 (251, '1020437f3495ce43edc5a85208ee60cf', 'Youtube', '1020437f3495ce43edc5a85208ee60cf', datetime.datetime(2019, 7, 18, 20, 29, 57), 89),
 (251, '51ec0e93aa36ff91430519184ad6f244', 'Naver', '51ec0e93aa36ff91430519184ad6f244', datetime.datetime(2019, 7, 19, 16, 1, 16, 17000), 90),
 (251, 'e027ffbf4c1d80802a64ca25f39caa8d', 'Organic', 'e027ffbf4c1d80802a64ca25f39caa8d', datetime.datetime(2019, 7, 19, 17, 38, 53), 91),
 (251, '57c50209953cb4fb4c0e9b9631f3802c', 'Instagram', '57c50209953cb4fb4c0e9b9631f3802c', datetime.datetime(2019, 7, 19, 17, 40, 18), 92),
 (251, '597a30669470a5825ac4655a8aeb8289', 'Instagram', '597a30669470a5825ac4655a8aeb8289', datetime.datetime(2019, 7, 19, 17, 41, 51), 93),
 (251, '8ecb8ebb08e20837963e95b2d8eded47', 'Youtube', '8ecb8ebb08e20837963e95b2d8eded47', datetime.datetime(2019, 7, 19, 17, 43, 51), 94),
 (251, '4585ad1e2cbe41891c011a3e0e73e1d4', 'Naver', '4585ad1e2cbe41891c011a3e0e73e1d4', datetime.datetime(2019, 7, 20, 12, 57, 48, 747000), 95),
 (251, '80a3f634893bdf5d63c679e5f99182b2', 'Instagram', '80a3f634893bdf5d63c679e5f99182b2', datetime.datetime(2019, 7, 20, 13, 1, 13, 857000), 96),
 (251, '3ec501b562c6038d2ffabafcbac37cd3', 'Instagram', '3ec501b562c6038d2ffabafcbac37cd3', datetime.datetime(2019, 7, 21, 12, 53, 14, 990000), 97),
 (251, 'efe2d4536fbb724f90ef5135b2899251', 'Youtube', 'efe2d4536fbb724f90ef5135b2899251', datetime.datetime(2019, 7, 22, 13, 19, 23, 447000), 98),
 (251, '20004d9171f2c39562975a104b3b9d7d', 'Naver', '20004d9171f2c39562975a104b3b9d7d', datetime.datetime(2019, 7, 23, 12, 47, 7, 460000), 99),
 (251, '8fd2aa96c03c97513ead09138475efd9', 'Google', '8fd2aa96c03c97513ead09138475efd9', datetime.datetime(2019, 7, 24, 12, 54, 51, 497000), 100),
 (251, '4bfc7637274e584b7752e3fd7bd275e7', 'Google', '4bfc7637274e584b7752e3fd7bd275e7', datetime.datetime(2019, 7, 24, 16, 8, 42), 101),
 (251, 'd3d92bc35d062c83f89b7ea87d99dca9', 'Instagram', 'd3d92bc35d062c83f89b7ea87d99dca9', datetime.datetime(2019, 7, 25, 12, 34, 51, 103000), 102),
 (251, 'f5685cb5d80c3249a9770cfd98cf71eb', 'Instagram', 'f5685cb5d80c3249a9770cfd98cf71eb', datetime.datetime(2019, 7, 25, 12, 39, 35, 593000), 103),
 (251, '9c108d0cb8dd18ea82733a05930b1aed', 'Instagram', '9c108d0cb8dd18ea82733a05930b1aed', datetime.datetime(2019, 7, 26, 12, 47, 35, 500000), 104),
 (251, '81eb580fa587a1c8eef8291c0075182e', 'Organic', '81eb580fa587a1c8eef8291c0075182e', datetime.datetime(2019, 7, 26, 12, 52, 22, 50000), 105),
 (251, '3530af42dc880d61af906cf5b3c9bde1', 'Google', '3530af42dc880d61af906cf5b3c9bde1', datetime.datetime(2019, 7, 26, 19, 18, 38), 106),
 (251, '107aca10b9fd0bb976953ad54c934f05', 'Google', '107aca10b9fd0bb976953ad54c934f05', datetime.datetime(2019, 7, 27, 13, 33, 2, 323000), 107),
 (251, '89ba5a9ed3d76c448fed83a18275b451', 'Facebook', '89ba5a9ed3d76c448fed83a18275b451', datetime.datetime(2019, 7, 29, 13, 6, 27, 130000), 108),
 (251, 'a4de67584a6420f7c296da3dee64f99b', 'Google', 'a4de67584a6420f7c296da3dee64f99b', datetime.datetime(2019, 7, 30, 12, 23, 24, 593000), 109),
 (251, 'c5e0299714bda49d29f444c4ac527453', 'Instagram', 'c5e0299714bda49d29f444c4ac527453', datetime.datetime(2019, 7, 30, 15, 31, 25), 110),
 (251, 'e6effb67cd9e11866f4b9c5b6ed8c1b7', 'Facebook', 'e6effb67cd9e11866f4b9c5b6ed8c1b7', datetime.datetime(2019, 7, 31, 13, 38, 48, 527000), 111),
 (251, 'ec1f683c45a79133908f2826a29176e5', 'Google', 'ec1f683c45a79133908f2826a29176e5', datetime.datetime(2019, 8, 1, 12, 56, 52, 543000), 112),
 (251, '54e6004b6582e10b9133900cf885a313', 'Naver', '54e6004b6582e10b9133900cf885a313', datetime.datetime(2019, 8, 2, 13, 32, 39, 743000), 113),
 (251, '245403f0ec118644e403ddd11c5797e9', 'Youtube', '245403f0ec118644e403ddd11c5797e9', datetime.datetime(2019, 8, 3, 14, 2, 1, 400000), 114),
 (251, 'c42bd6650f37513f5375dd4e9414b359', 'Instagram', 'c42bd6650f37513f5375dd4e9414b359', datetime.datetime(2019, 8, 4, 13, 53, 54, 553000), 115),
 (251, '427d99addb45f263ba569a7a2d9c65a3', 'Organic', '427d99addb45f263ba569a7a2d9c65a3', datetime.datetime(2019, 8, 5, 12, 37, 58, 720000), 116),
 (251, 'c86c4404d6c078face600eda09b12443', 'Youtube', 'c86c4404d6c078face600eda09b12443', datetime.datetime(2019, 8, 6, 12, 47, 42, 17000), 117),
 (251, 'f8c7555d2671b87529f7fb9b43fd0b71', 'Facebook', 'f8c7555d2671b87529f7fb9b43fd0b71', datetime.datetime(2019, 8, 7, 12, 42, 7, 713000), 118),
 (251, '957e130db9f020497e59a4169fca3ba5', 'Instagram', '957e130db9f020497e59a4169fca3ba5', datetime.datetime(2019, 8, 8, 12, 7, 18, 430000), 119),
 (251, '77dd1e39a455f1c57e984f7fe30b59b9', 'Organic', '77dd1e39a455f1c57e984f7fe30b59b9', datetime.datetime(2019, 8, 9, 13, 19, 19, 580000), 120),
 (251, 'd7c93750864d8558583e2fc46620a0d2', 'Organic', 'd7c93750864d8558583e2fc46620a0d2', datetime.datetime(2019, 8, 10, 14, 3, 46, 323000), 121),
 (251, '57b3c556c09ac06cd6e1b4db8ae208e4', 'Naver', '57b3c556c09ac06cd6e1b4db8ae208e4', datetime.datetime(2019, 8, 11, 13, 57, 58, 377000), 122),
 (251, '33e70269806c88720e2d89ed1d3f1be3', 'Instagram', '33e70269806c88720e2d89ed1d3f1be3', datetime.datetime(2019, 8, 12, 12, 46, 55, 367000), 123),
 (251, '3f3cd9d773c7ec9516bc0b9fff6ed5bd', 'Instagram', '3f3cd9d773c7ec9516bc0b9fff6ed5bd', datetime.datetime(2019, 8, 13, 12, 22, 28, 127000), 124),
 (251, 'f8327b26a178ba557a59ace3378c2f95', 'Instagram', 'f8327b26a178ba557a59ace3378c2f95', datetime.datetime(2019, 8, 14, 12, 10, 21, 790000), 125),
 (251, '7cc9dfab96e5f47acc9bb48d36f1cac7', 'Naver', '7cc9dfab96e5f47acc9bb48d36f1cac7', datetime.datetime(2019, 8, 15, 17, 28, 48, 497000), 126),
 (251, '64bc5de04c2d2dee8c16bc2eb87d4ea2', 'Instagram', '64bc5de04c2d2dee8c16bc2eb87d4ea2', datetime.datetime(2019, 8, 16, 13, 54, 53, 113000), 127),
 (251, '254b64c2f1b76e3c54a0058e36592548', 'Instagram', '254b64c2f1b76e3c54a0058e36592548', datetime.datetime(2019, 8, 17, 14, 11, 54, 877000), 128),
 (251, '4ddc41b4191e585aa81256b6a6bcf2bd', 'Organic', '4ddc41b4191e585aa81256b6a6bcf2bd', datetime.datetime(2019, 8, 18, 13, 38, 14, 420000), 129),
 (251, '6fdceb5c446f700471d211a98c875149', 'Youtube', '6fdceb5c446f700471d211a98c875149', datetime.datetime(2019, 8, 19, 13, 24, 12, 170000), 130),
 (251, '8962b25e779a30ecd4c5ed79e7b8efbd', 'Facebook', '8962b25e779a30ecd4c5ed79e7b8efbd', datetime.datetime(2019, 8, 20, 13, 33, 0, 347000), 131),
 (251, '051b924caaec65378fb0ef6356723e13', 'Facebook', '051b924caaec65378fb0ef6356723e13', datetime.datetime(2019, 8, 21, 13, 34, 23, 947000), 132),
 (251, '6ce498d47558ebcbc27fdeda6d64b905', 'Google', '6ce498d47558ebcbc27fdeda6d64b905', datetime.datetime(2019, 8, 21, 13, 37, 4, 953000), 133),
 (251, '7ecda7d8d9f5f72039bde6f760039c82', 'Google', '7ecda7d8d9f5f72039bde6f760039c82', datetime.datetime(2019, 8, 22, 12, 36, 23, 127000), 134),
 (251, '7faa6534e1d63c4c2c4b318135100acf', 'Facebook', '7faa6534e1d63c4c2c4b318135100acf', datetime.datetime(2019, 8, 23, 14, 0, 1, 60000), 135),
 (251, 'd9be23a7ea5cbdaf51e41248813e57e8', 'Organic', 'd9be23a7ea5cbdaf51e41248813e57e8', datetime.datetime(2019, 8, 25, 14, 58, 40, 387000), 136),

Assignment - 2 - Gross Revenue가 가장 큰 UserID 10개 찾기

Table
Fields
session_timestamp   - 
sessionid (string), **ts (timestamp)**

user_session_channel  - 
**userid (integer)**, sessionid (string), channel (string)

session_transaction   - 
sessionid (string), **refunded (boolean), amount (integer)**

In [63]:
%%sql 

SELECT * 
FROM raw_data.session_transaction
LIMIT 10

 * postgresql://gayoungjang:***@grepp-data.cduaw970ssvt.ap-northeast-2.redshift.amazonaws.com:5439/dev
10 rows affected.

[('00029153d12ae1c9abe59c17ff2e0895', False, 85),
 ('008909bd27b680698322c750c400e4b1', False, 13),
 ('0107acb41ef20db2289d261d4e34fd38', False, 16),
 ('018544a2c48077d2cc3ce3278ab1e805', False, 39),
 ('020c38173caff02033564200e0288aa9', False, 61),
 ('029591145fad252b28d844d823097400', False, 13),
 ('03190309cbcd7161a426abd4782bdcd2', False, 75),
 ('03a13aa6921aed989b31d92dc73b391a', False, 129),
 ('04215c1ad3aaff3ed175446d2ea3c0f2', False, 99),
 ('049b8c570e6cc662b4a3d7e3c86e236f', False, 24)]

In [65]:
%%sql 

SELECT COUNT(1) 
FROM raw_data.session_transaction

 * postgresql://gayoungjang:***@grepp-data.cduaw970ssvt.ap-northeast-2.redshift.amazonaws.com:5439/dev
1 rows affected.

[(996,)]

In [66]:
%%sql 

SELECT count(1)
FROM raw_data.session_transaction
WHERE refunded is TRUE

 * postgresql://gayoungjang:***@grepp-data.cduaw970ssvt.ap-northeast-2.redshift.amazonaws.com:5439/dev
1 rows affected.

[(54,)]

In [67]:
%%sql

SELECT count(1)
FROM raw_data.user_session_channel

 * postgresql://gayoungjang:***@grepp-data.cduaw970ssvt.ap-northeast-2.redshift.amazonaws.com:5439/dev
1 rows affected.

[(101520,)]

In [77]:
%%sql

SELECT 
  sessionid,
  CASE
    WHEN refunded is TRUE THEN amount *(-1)
    WHEN refunded is NOT TRUE THEN amount  
  END gross_amount
FROM raw_data.session_transaction
LIMIT 10

 * postgresql://gayoungjang:***@grepp-data.cduaw970ssvt.ap-northeast-2.redshift.amazonaws.com:5439/dev
10 rows affected.

[('004152a48f6de777a672457f3619da9d', 149),
 ('00c37b7a1f13daf967813da9b68937f3', 138),
 ('014a5f8619d8704745b8505140f2a1a7', 80),
 ('01c2bff254aa9799912374128532e5b3', 142),
 ('024da127a13f0f5fd374ee98bd052ce7', 54),
 ('02d9ece9b8124af667964175280109d3', 7),
 ('0361f1baaa8ed070dfe62ae2245bcbed', 96),
 ('03e0d5f0c8b9b7b78532779f6ca94209', 122),
 ('045a55c409fd464e10585c925532138b', 80),
 ('04dc6557c76932830029fa4348db8690', 133)]

In [86]:
%%sql

SELECT u.userid, SUM(amount)
FROM raw_data.session_transaction g
JOIN raw_data.user_session_channel u ON g.sessionid = u.sessionid
GROUP BY 1
ORDER BY 2
LIMIT 10

 * postgresql://gayoungjang:***@grepp-data.cduaw970ssvt.ap-northeast-2.redshift.amazonaws.com:5439/dev
10 rows affected.

[(989, 743),
 (772, 556),
 (1615, 506),
 (654, 488),
 (1651, 463),
 (973, 438),
 (262, 422),
 (1099, 421),
 (2682, 414),
 (891, 412)]

In [90]:
%%sql

WITH gross AS (
    SELECT 
      sessionid,
      CASE
        WHEN refunded is TRUE THEN amount *(-1)
        WHEN refunded is NOT TRUE THEN amount  
      END gross_amount
    FROM raw_data.session_transaction
)
SELECT u.userid, SUM(g.gross_amount)
FROM gross g
JOIN raw_data.user_session_channel u ON g.sessionid = u.sessionid
GROUP BY 1
ORDER BY 2 DESC
LIMIT 10

 * postgresql://gayoungjang:***@grepp-data.cduaw970ssvt.ap-northeast-2.redshift.amazonaws.com:5439/dev
10 rows affected.

[(989, 743),
 (772, 556),
 (1615, 506),
 (654, 488),
 (1651, 463),
 (973, 438),
 (262, 422),
 (2682, 414),
 (891, 412),
 (1085, 411)]

채널별 월 매출액 테이블 만들기 

month
channel
uniqueUsers (총방문 사용자)
paidUsers (구매 사용자: refund한 경우도 판매로 고려)
conversionRate (구매사용자 / 총방문 사용자)
grossRevenue (refund 포함)
netRevenue (refund 제외)

 session_timestamp   -
sessionid (string), **ts (timestamp)**

user_session_channel    -
**userid (integer)**, sessionid (string), channel (string)

session_transaction    -
sessionid (string), **refunded (boolean), amount (integer)**

channel    -
**channelname (string)**

In [92]:
%%sql

--- Month info from session_timestamp

SELECT ts, EXTRACT(MONTH FROM ts) as month, sessionid
FROM raw_data.session_timestamp
LIMIT 10

 * postgresql://gayoungjang:***@grepp-data.cduaw970ssvt.ap-northeast-2.redshift.amazonaws.com:5439/dev
10 rows affected.

[(datetime.datetime(2019, 5, 1, 0, 35, 59, 897000), 5, 'c41dd99a69df04044aa4e33ece9c9249'),
 (datetime.datetime(2019, 5, 1, 2, 53, 48, 503000), 5, 'fdc0eb412a84fa549afe68373d9087e9'),
 (datetime.datetime(2019, 5, 1, 12, 18, 26, 637000), 5, '0a54b19a13b6712dc04d1b49215423d8'),
 (datetime.datetime(2019, 5, 1, 13, 41, 29, 267000), 5, 'a914ecef9c12ffdb9bede64bb703d877'),
 (datetime.datetime(2019, 5, 1, 14, 17, 54, 83000), 5, '05ae14d7ae387b93370d142d82220f1b'),
 (datetime.datetime(2019, 5, 1, 14, 42, 50, 487000), 5, 'eddeb82df22554fa67c641e3f8a25566'),
 (datetime.datetime(2019, 5, 1, 15, 8, 15, 557000), 5, '4c4ea5258ef3fb3fb1fc48fee9b4408c'),
 (datetime.datetime(2019, 5, 1, 15, 20, 27, 377000), 5, '8ae1da0fe37c98412768453f82490da2'),
 (datetime.datetime(2019, 5, 1, 15, 53, 7, 17000), 5, '60131a2a3f223dc8f4753bcc5771660c'),
 (datetime.datetime(2019, 5, 1, 16, 15, 43, 423000), 5, '90f4760fcc9b69c13da7368c5c2917f3')]

In [93]:
%%sql

--- Monthly session_timestamp count

SELECT EXTRACT(MONTH FROM ts) as month, count(sessionid)
FROM raw_data.session_timestamp
GROUP BY 1

 * postgresql://gayoungjang:***@grepp-data.cduaw970ssvt.ap-northeast-2.redshift.amazonaws.com:5439/dev
7 rows affected.

[(5, 6261),
 (7, 14840),
 (9, 15790),
 (10, 18899),
 (6, 10520),
 (8, 17151),
 (11, 18059)]

In [97]:
%%sql 

-- total unique users

SELECT count(DISTINCT userid) as uniqueUsers
FROM raw_data.user_session_channel

 * postgresql://gayoungjang:***@grepp-data.cduaw970ssvt.ap-northeast-2.redshift.amazonaws.com:5439/dev
1 rows affected.

[(949,)]

In [98]:
%%sql

-- total paid users
SELECT count(DISTINCT userid) as paidUsers
FROM raw_data.user_session_channel A
JOIN raw_data.session_transaction B ON A.sessionid = B.sessionid

 * postgresql://gayoungjang:***@grepp-data.cduaw970ssvt.ap-northeast-2.redshift.amazonaws.com:5439/dev
1 rows affected.

[(534,)]

In [103]:
%%sql
-- Monthly unique user count per channel

SELECT c.channelname, EXTRACT(MONTH FROM ts) as month, COUNT(DISTINCT userid) as uniqueUsers
FROM raw_data.user_session_channel A
LEFT JOIN raw_data.session_timestamp B ON A.sessionid = B.sessionid
FULL JOIN raw_data.channel C ON A.channel = C.channelname
GROUP BY 1, 2
ORDER BY 1,2

 * postgresql://gayoungjang:***@grepp-data.cduaw970ssvt.ap-northeast-2.redshift.amazonaws.com:5439/dev
43 rows affected.

[('Facebook', 5, 247),
 ('Facebook', 6, 414),
 ('Facebook', 7, 558),
 ('Facebook', 8, 611),
 ('Facebook', 9, 597),
 ('Facebook', 10, 698),
 ('Facebook', 11, 688),
 ('Google', 5, 253),
 ('Google', 6, 412),
 ('Google', 7, 556),
 ('Google', 8, 610),
 ('Google', 9, 599),
 ('Google', 10, 699),
 ('Google', 11, 688),
 ('Instagram', 5, 234),
 ('Instagram', 6, 410),
 ('Instagram', 7, 567),
 ('Instagram', 8, 621),
 ('Instagram', 9, 588),
 ('Instagram', 10, 707),
 ('Instagram', 11, 669),
 ('Naver', 5, 237),
 ('Naver', 6, 398),
 ('Naver', 7, 553),
 ('Naver', 8, 626),
 ('Naver', 9, 592),
 ('Naver', 10, 713),
 ('Naver', 11, 667),
 ('Organic', 5, 238),
 ('Organic', 6, 416),
 ('Organic', 7, 557),
 ('Organic', 8, 608),
 ('Organic', 9, 592),
 ('Organic', 10, 709),
 ('Organic', 11, 677),
 ('TIKTOK', None, 0),
 ('Youtube', 5, 244),
 ('Youtube', 6, 400),
 ('Youtube', 7, 564),
 ('Youtube', 8, 614),
 ('Youtube', 9, 588),
 ('Youtube', 10, 705),
 ('Youtube', 11, 677)]

In [111]:
%%sql

-- gorssRevenue and netRevenue
WITH gross AS (
    SELECT 
      sessionid,
      CASE
        WHEN refunded is TRUE THEN amount *(-1)
        WHEN refunded is NOT TRUE THEN amount  
      END gross_amount,
      amount
    FROM raw_data.session_transaction
)
SELECT EXTRACT(MONTH FROM s.ts) as month, u.userid, SUM(g.amount) as netRevenue, SUM(g.gross_amount) as grossRevenue
FROM gross g
JOIN raw_data.user_session_channel u ON g.sessionid = u.sessionid
JOIN raw_data.session_timestamp s ON s.sessionid = g.sessionid
GROUP BY 1,2
ORDER BY 2 
LIMIT 10

 * postgresql://gayoungjang:***@grepp-data.cduaw970ssvt.ap-northeast-2.redshift.amazonaws.com:5439/dev
10 rows affected.

[(6, 27, 127, 127),
 (6, 29, 118, 118),
 (5, 34, 88, 88),
 (7, 34, 92, 92),
 (7, 36, 41, 41),
 (10, 40, 70, -70),
 (9, 41, 32, 32),
 (5, 44, 92, 92),
 (10, 45, 39, 39),
 (8, 45, 112, -112)]

In [118]:
%%sql 

SELECT EXTRACT(MONTH FROM ts) as month, userid, amount, refunded
FROM raw_data.session_transaction A
JOIN raw_data.session_timestamp B ON A.sessionid = B.sessionid
JOIN raw_data.user_session_channel C ON A.sessionid = C.sessionid
WHERE userid IN (40,41,45)
--GROUP BY 1, 2

 * postgresql://gayoungjang:***@grepp-data.cduaw970ssvt.ap-northeast-2.redshift.amazonaws.com:5439/dev
4 rows affected.

[(8, 45, 112, True),
 (9, 41, 32, False),
 (10, 45, 39, False),
 (10, 40, 70, True)]

In [136]:
%%sql

WITH gross AS (
  SELECT
    sessionid,
    CASE
      WHEN refunded is TRUE THEN amount *(-1)
      WHEN refunded is NOT TRUE THEN amount
    END gross_amount,
    refunded,
    amount
  FROM
    raw_data.session_transaction
)
SELECT
  u.channel,
  EXTRACT(
    MONTH
    FROM
      s.ts
  ) as month,
  COUNT(DISTINCT u.userid) as uniqueUsers,
  COUNT(CASE WHEN g.gross_amount > 0 THEN 1 END) as paidUsers,  -- User Distinct missing due to COUNTIF function
  SUM(g.amount) as netRevenue,
  SUM(g.gross_amount) as grossRevenue
FROM
  gross g
  JOIN raw_data.user_session_channel u ON g.sessionid = u.sessionid
  JOIN raw_data.session_timestamp s ON s.sessionid = g.sessionid
GROUP BY
  1,
  2
ORDER BY
  2
LIMIT
  10;

 * postgresql://gayoungjang:***@grepp-data.cduaw970ssvt.ap-northeast-2.redshift.amazonaws.com:5439/dev
10 rows affected.

[('Organic', 5, 17, 16, 1846, 1296),
 ('Youtube', 5, 10, 9, 529, 529),
 ('Naver', 5, 11, 10, 867, 821),
 ('Instagram', 5, 11, 9, 959, 581),
 ('Google', 5, 10, 10, 580, 580),
 ('Facebook', 5, 14, 11, 1199, 795),
 ('Facebook', 6, 22, 22, 1578, 1578),
 ('Google', 6, 13, 13, 947, 947),
 ('Naver', 6, 15, 16, 1090, 1090),
 ('Youtube', 6, 17, 17, 1042, 1042)]

In [140]:
%%sql

CREATE TABLE gayoungjang.gajang02 AS 
SELECT
  channelname,
  EXTRACT(
    MONTH
    FROM
      ts
  ) as month,
  COUNT(DISTINCT userid) as uniqueUsers,
  COUNT(
    CASE
      WHEN refunded is FALSE THEN 1
    END
  ) as paidUsers,
  CASE
    
      WHEN uniqueUsers = 0 THEN 0
      ELSE CAST(paidUsers as FLOAT) / uniqueUsers 
    END
   as conversionRate,
  SUM(amount) as netRevenue,
  SUM(
    amount * CASE
      WHEN refunded is TRUE THEN -1
      ELSE 1
    END
  ) as grossRevenue
FROM
  raw_data.user_session_channel u
  LEFT JOIN raw_data.session_timestamp t ON u.sessionid = t.sessionid
  LEFT JOIN raw_data.session_transaction s ON u.sessionid = s.sessionid FULL
  JOIN raw_data.channel c ON u.channel = c.channelname
GROUP BY
  1,
  2
ORDER BY 1,2

 * postgresql://gayoungjang:***@grepp-data.cduaw970ssvt.ap-northeast-2.redshift.amazonaws.com:5439/dev
Done.

[]